# 2019년

## 데이터 전처리

### 데이터 수집 비율
- 2019년도 제주 여행자를 대상으로 한 방문 관광객 실태조사에서 응답자 프로파일을 가져옴.
  + 응답자 프로파일의 카테고리 중 월별, 연령별 카테고리만 수집함.
- **해당 연도의 데이터 수집 대상 비율을 명시해 앞으로 다룰 데이터들이 어떤 방식으로 추출되었는지 설명함.**

In [91]:
import pandas as pd

DATA_path = '/content/drive/MyDrive/세프/DATA/'

profile_df = pd.read_excel(DATA_path + '2019년 응답자 프로파일')
profile_df.head()

  table Unnamed: 1 Unnamed: 2 Unnamed: 3
0   NaN        NaN        사례수          %
1  [전체]        NaN       6133        100
2    월별        01월        463        7.6
3    월별        02월        452        7.4
4    월별        03월        470        7.7

In [92]:
profile_df = profile_df.drop(index = 0)
profile_df.head()

  table Unnamed: 1 Unnamed: 2 Unnamed: 3
1  [전체]        NaN       6133        100
2    월별        01월        463        7.6
3    월별        02월        452        7.4
4    월별        03월        470        7.7
5    월별        04월        524        8.5

In [93]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '비율(%)'}

profile_df = profile_df.rename(columns = columns)
profile_df

   분석 카테고리       세부 카테고리   사례수 비율(%)
1     [전체]           NaN  6133   100
2       월별           01월   463   7.6
3       월별           02월   452   7.4
4       월별           03월   470   7.7
5       월별           04월   524   8.5
6       월별           05월   532   8.7
7       월별           06월   523   8.5
8       월별           07월   524   8.5
9       월별           08월   562   9.2
10      월별           09월   467   7.6
11      월별           10월   567   9.3
12      월별           11월   533   8.7
13      월별           12월   516   8.4
14     거주지         서울특별시  1422  23.2
15     거주지         부산광역시   576   9.4
16     거주지         대구광역시   369     6
17     거주지         인천광역시   390   6.4
18     거주지         광주광역시   168   2.7
19     거주지         대전광역시   184     3
20     거주지         울산광역시   187     3
21     거주지         세종자치시    76   1.2
22     거주지           경기도  1494  24.4
23     거주지           강원도    53   0.9
24     거주지           충청도   289   4.7
25     거주지           전라도   553     9
26     거주지           경상도   357   5.8
27     거주지  해외거주 등 기타 지역    16   0.3
28      성별            남자  2400  39.1
29      성별            여자  3733  60.9
30      연령     15세 - 20세    70   1.1
31      연령     21세 - 30세  1376  22.4
32      연령     31세 - 40세  1503  24.5
33      연령     41세 - 50세  1352    22
34      연령     51세 - 60세  1469  23.9
35      연령        61세 이상   364   5.9
36    방문목적     휴가 및 순수여행  5845  95.3
37    방문목적        비즈니스여행   194   3.2
38    방문목적          기타여행    94   1.5
39    여행형태          개별여행  5909  96.3
40    여행형태         패키지여행   203   3.3
41    여행형태       부분패키지여행    21   0.3
42    방문횟수            1회  1863  30.4
43    방문횟수            2회  2546  41.5
44    방문횟수            3회   830  13.5
45    방문횟수         4회 이상   894  14.6

In [94]:
profile_df = profile_df.drop(index=range(14, 30)).reset_index(drop=True)

profile_df

   분석 카테고리    세부 카테고리   사례수 비율(%)
0     [전체]        NaN  6133   100
1       월별        01월   463   7.6
2       월별        02월   452   7.4
3       월별        03월   470   7.7
4       월별        04월   524   8.5
5       월별        05월   532   8.7
6       월별        06월   523   8.5
7       월별        07월   524   8.5
8       월별        08월   562   9.2
9       월별        09월   467   7.6
10      월별        10월   567   9.3
11      월별        11월   533   8.7
12      월별        12월   516   8.4
13      연령  15세 - 20세    70   1.1
14      연령  21세 - 30세  1376  22.4
15      연령  31세 - 40세  1503  24.5
16      연령  41세 - 50세  1352    22
17      연령  51세 - 60세  1469  23.9
18      연령     61세 이상   364   5.9
19    방문목적  휴가 및 순수여행  5845  95.3
20    방문목적     비즈니스여행   194   3.2
21    방문목적       기타여행    94   1.5
22    여행형태       개별여행  5909  96.3
23    여행형태      패키지여행   203   3.3
24    여행형태    부분패키지여행    21   0.3
25    방문횟수         1회  1863  30.4
26    방문횟수         2회  2546  41.5
27    방문횟수         3회   830  13.5
28    방문횟수      4회 이상   894  14.6

- 전처리가 완료된 응답자 프로파일.
  + 월별, 연령별로 나눠진 사례들의 비율이 모두 비슷하게 퍼져있음을 확인할 수 있다.
  + 단, 61세 이상 부분에만 층화추출을 적용한 것으로 확인된다.

In [95]:
profile_df = profile_df.drop(index=range(19, 29)).reset_index(drop=True)

profile_df

   분석 카테고리    세부 카테고리   사례수 비율(%)
0     [전체]        NaN  6133   100
1       월별        01월   463   7.6
2       월별        02월   452   7.4
3       월별        03월   470   7.7
4       월별        04월   524   8.5
5       월별        05월   532   8.7
6       월별        06월   523   8.5
7       월별        07월   524   8.5
8       월별        08월   562   9.2
9       월별        09월   467   7.6
10      월별        10월   567   9.3
11      월별        11월   533   8.7
12      월별        12월   516   8.4
13      연령  15세 - 20세    70   1.1
14      연령  21세 - 30세  1376  22.4
15      연령  31세 - 40세  1503  24.5
16      연령  41세 - 50세  1352    22
17      연령  51세 - 60세  1469  23.9
18      연령     61세 이상   364   5.9

### 1인당 지출 경비 전처리
- 1인당 지출 경비에 대한 카테고리 : 전체 부분, 숙박 부분, 식음료 부분, 항공/선박 부분, 관광/문화 지출 부분
- **1인당 지출 경비 부분이 지출 기준인원 항목의 하위 항목으로 분류되어 있어 응답자 프로파일처럼 해당 데이터의 비율을 명시함.**

In [96]:
expenditure_standard = pd.read_excel(DATA_path + '2019년 지출 기준인원 - 1인당 지출 경비에 대한 상위 항목.xlsx')
expenditure_standard

,table,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,10명,11명 이상,[평균]
1,[전체],NaN,6133,8.4,31,13.7,21,6,6,3.1,4.1,1.6,1.7,3.5,3.96
2,월별,01월,463,4.7,30.6,15,23.6,6.8,7.6,1.8,2.6,0.2,1.9,5.3,4.13
3,월별,02월,452,3.5,22.8,13.6,23.2,9.8,7.5,5.3,6,3.8,1.4,3.1,4.53
4,월별,03월,470,6.3,41.3,13.7,20.1,6.4,3.8,1.7,3.5,1,0.8,1.4,3.51
5,월별,04월,524,4.2,18.3,17.1,22,7.5,9.2,3.4,8.5,2.5,3,4.4,4.76
6,월별,05월,532,4.1,26.8,12.5,21.4,8.2,8.2,3.5,5.4,2.2,2.1,5.6,4.51
7,월별,06월,523,5.7,27.3,14,19.8,5.6,7.9,4.3,4.8,3.5,2.7,4.6,4.4
8,월별,07월,524,6.8,33.1,14.6,22,4.6,5.7,3.2,3.2,0.9,1.5,4.3,3.95
9,월별,08월,562,4.6,39.7,16.4,22.9,6.1,3.7,3.2,0.9,1.2,0.3,1,3.34
10,월별,09월,467,18.5,37,15.7,15.7,3.9,2,1.4,1.4,1.4,0.7,2.4,3.19
11,월별,10월,567,14.9,27,9.7,21.1,4.4,6.1,4.1,7.1,0,1.7,4,3.96
12,월별,11월,533,14.7,34.4,10.5,22.6,4.4,3.6,2.8,1.6,1.7,2.1,1.7,3.39
13,월별,12월,516,12.5,33.8,11.9,17.1,5.2,6.8,1.9,3.5,1.5,1.9,4,3.85
14,거주지,서울특별시,1422,9.5,33.3,14.6,20,6.2,4.9,3.2,3.5,1,1.2,2.6,3.67
15,거주지,부산광역시,576,6.4,30.4,10.4,26.9,6.4,6.3,2.9,3.9,1.2,1.6,3.7,4.02
16,거주지,대구광역시,369,6.4,29.5,17.6,19.8,4.9,5.7,2.9,6.2,1.6,2.3,3.1,4.06
17,거주지,인천광역시,390,7.6,28.7,17.2,24.2,4,7.9,2.1,3.4,0.9,1.8,2.2,3.74
18,거주지,광주광역시,168,11.5,27.5,8.8,16.3,10,8.9,3.6,2.8,4.9,3.7,1.9,4.21
19,거주지,대전광역시,184,10.2,32,10.9,18.5,6.3,4.4,2.6,7.7,0.8,2,4.7,4.17
20,거주지,울산광역시,187,1.2,25.9,7.9,26.8,8.6,12,4.7,4.9,0.6,1.4,6,4.72
21,거주지,세종자치시,76,6.5,29,10.9,21.3,3,14.2,1.5,6.3,3.1,0.5,3.7,4.27
22,거주지,경기도,1494,7.7,34.6,17,21.2,4.5,5.3,2.2,2.2,1.6,0.7,3,3.6
23,거주지,강원도,53,8.5,36.8,2.4,25.9,6.5,8.5,2.4,2.1,4.7,0,2.3,3.9
24,거주지,충청도,289,16.9,25.5,10.1,13.2,6.6,4.3,3.2,6.8,2.8,3.9,6.7,4.35
25,거주지,전라도,553,8,29,8.1,18.3,7.8,7.3,4.2,6.2,2.6,3.1,5.5,4.7
26,거주지,경상도,357,8.2,22,14.8,22.8,8.3,4.8,4.5,5.4,2.4,2.9,3.8,4.52
27,거주지,해외거주 등 기타 지역,16,15.5,32.2,1.2,6.6,15.1,7.3,15.5,6.6,0,0,0,3.9
28,성별,남자,2400,10.6,30.7,11.1,21.7,5.7,5.6,3.1,4.1,1.3,2,4,3.99
29,성별,여자,3733,7,31.1,15.3,20.5,6.3,6.3,3,4,1.8,1.5,3.2,3.94
30,연령,15세 - 20세,70,31.3,21,6.8,26.9,6.6,1.8,0,0,1.8,0,3.7,3.29
31,연령,21세 - 30세,1376,6.2,62,14.1,11.3,2.7,1.6,0.4,0.9,0.4,0.1,0.3,2.59
32,연령,31세 - 40세,1503,7.6,29.8,22.2,21.1,6,3.9,2.9,2.1,0.9,0.7,2.8,3.59
33,연령,41세 - 50세,1352,7.5,13.5,11.6,30.8,7.1,9.5,5.1,5.3,2.5,2.8,4.5,4.71
34,연령,51세 - 60세,1469,9.6,18.2,8.8,23.1,8.2,8.7,4.5,7.7,2.2,2.8,6.2,4.93
35,연령,61세 이상,364,14.2,36.7,5.7,10.8,5.9,8.2,1.4,5.7,4,3.8,3.6,4.07
36,방문목적,휴가 및 순수여행,5845,6.4,31.4,13.8,21.7,6.2,6.2,3.2,4.2,1.7,1.7,3.5,4.03
37,방문목적,비즈니스여행,194,46.4,19.7,12.4,7.7,2.5,2.5,0,2.9,0,1.3,4.6,2.87
38,방문목적,기타여행,94,54.4,25.9,7.9,5.4,1.2,2.5,2.3,0,0,0,0.3,2.04
39,여행형태,개별여행,5909,5.5,32,14.2,21.7,6.2,6.2,3.2,4.1,1.7,1.8,3.4,4.02
40,여행형태,패키지여행,203,88.7,2.5,0,1.2,0.1,1.2,0,1.2,0,0,5.1,2.19
41,여행형태,부분패키지여행,21,45.2,21.4,5.1,10.4,5.6,0,0,11.2,0,0,1.1,3.82
42,방문횟수,1회,1863,7.7,29.9,13.8,20.4,6.4,7.2,3.2,4.5,1.7,2.1,3.2,4.03
43,방문횟수,2회,2546,4.9,31.7,15,21.7,6.5,5.8,3,4,1.7,1.4,4.2,4.05
44,방문횟수,3회,830,10,31,11.9,22.2,5.5,5.4,4.9,3,1.6,1.7,2.9,3.95
45,방문횟수,4회 이상,894,18.3,31,11.4,19,4.6,4.5,1.1,4.2,1.6,1.8,2.5,3.58
46,♠BASE : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '1명',
           'Unnamed: 4' : '2명',
           'Unnamed: 5' : '3명',
           'Unnamed: 6' : '4명',
           'Unnamed: 7' : '5명',
           'Unnamed: 8' : '6명',
           'Unnamed: 9' : '7명',
           'Unnamed: 10' : '8명',
           'Unnamed: 11' : '9명',
           'Unnamed: 12' : '10명',
           'Unnamed: 13' : '11명 이상',
           'Unnamed: 14' : '평균'}

expenditure_standard = expenditure_standard.rename(columns = columns)
expenditure_standard

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,10명,11명 이상,평균
0,NaN,NaN,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,10명,11명 이상,[평균]
1,[전체],NaN,6133,8.4,31,13.7,21,6,6,3.1,4.1,1.6,1.7,3.5,3.96
2,월별,01월,463,4.7,30.6,15,23.6,6.8,7.6,1.8,2.6,0.2,1.9,5.3,4.13
3,월별,02월,452,3.5,22.8,13.6,23.2,9.8,7.5,5.3,6,3.8,1.4,3.1,4.53
4,월별,03월,470,6.3,41.3,13.7,20.1,6.4,3.8,1.7,3.5,1,0.8,1.4,3.51
5,월별,04월,524,4.2,18.3,17.1,22,7.5,9.2,3.4,8.5,2.5,3,4.4,4.76
6,월별,05월,532,4.1,26.8,12.5,21.4,8.2,8.2,3.5,5.4,2.2,2.1,5.6,4.51
7,월별,06월,523,5.7,27.3,14,19.8,5.6,7.9,4.3,4.8,3.5,2.7,4.6,4.4
8,월별,07월,524,6.8,33.1,14.6,22,4.6,5.7,3.2,3.2,0.9,1.5,4.3,3.95
9,월별,08월,562,4.6,39.7,16.4,22.9,6.1,3.7,3.2,0.9,1.2,0.3,1,3.34
10,월별,09월,467,18.5,37,15.7,15.7,3.9,2,1.4,1.4,1.4,0.7,2.4,3.19
11,월별,10월,567,14.9,27,9.7,21.1,4.4,6.1,4.1,7.1,0,1.7,4,3.96
12,월별,11월,533,14.7,34.4,10.5,22.6,4.4,3.6,2.8,1.6,1.7,2.1,1.7,3.39
13,월별,12월,516,12.5,33.8,11.9,17.1,5.2,6.8,1.9,3.5,1.5,1.9,4,3.85
14,거주지,서울특별시,1422,9.5,33.3,14.6,20,6.2,4.9,3.2,3.5,1,1.2,2.6,3.67
15,거주지,부산광역시,576,6.4,30.4,10.4,26.9,6.4,6.3,2.9,3.9,1.2,1.6,3.7,4.02
16,거주지,대구광역시,369,6.4,29.5,17.6,19.8,4.9,5.7,2.9,6.2,1.6,2.3,3.1,4.06
17,거주지,인천광역시,390,7.6,28.7,17.2,24.2,4,7.9,2.1,3.4,0.9,1.8,2.2,3.74
18,거주지,광주광역시,168,11.5,27.5,8.8,16.3,10,8.9,3.6,2.8,4.9,3.7,1.9,4.21
19,거주지,대전광역시,184,10.2,32,10.9,18.5,6.3,4.4,2.6,7.7,0.8,2,4.7,4.17
20,거주지,울산광역시,187,1.2,25.9,7.9,26.8,8.6,12,4.7,4.9,0.6,1.4,6,4.72
21,거주지,세종자치시,76,6.5,29,10.9,21.3,3,14.2,1.5,6.3,3.1,0.5,3.7,4.27
22,거주지,경기도,1494,7.7,34.6,17,21.2,4.5,5.3,2.2,2.2,1.6,0.7,3,3.6
23,거주지,강원도,53,8.5,36.8,2.4,25.9,6.5,8.5,2.4,2.1,4.7,0,2.3,3.9
24,거주지,충청도,289,16.9,25.5,10.1,13.2,6.6,4.3,3.2,6.8,2.8,3.9,6.7,4.35
25,거주지,전라도,553,8,29,8.1,18.3,7.8,7.3,4.2,6.2,2.6,3.1,5.5,4.7
26,거주지,경상도,357,8.2,22,14.8,22.8,8.3,4.8,4.5,5.4,2.4,2.9,3.8,4.52
27,거주지,해외거주 등 기타 지역,16,15.5,32.2,1.2,6.6,15.1,7.3,15.5,6.6,0,0,0,3.9
28,성별,남자,2400,10.6,30.7,11.1,21.7,5.7,5.6,3.1,4.1,1.3,2,4,3.99
29,성별,여자,3733,7,31.1,15.3,20.5,6.3,6.3,3,4,1.8,1.5,3.2,3.94
30,연령,15세 - 20세,70,31.3,21,6.8,26.9,6.6,1.8,0,0,1.8,0,3.7,3.29
31,연령,21세 - 30세,1376,6.2,62,14.1,11.3,2.7,1.6,0.4,0.9,0.4,0.1,0.3,2.59
32,연령,31세 - 40세,1503,7.6,29.8,22.2,21.1,6,3.9,2.9,2.1,0.9,0.7,2.8,3.59
33,연령,41세 - 50세,1352,7.5,13.5,11.6,30.8,7.1,9.5,5.1,5.3,2.5,2.8,4.5,4.71
34,연령,51세 - 60세,1469,9.6,18.2,8.8,23.1,8.2,8.7,4.5,7.7,2.2,2.8,6.2,4.93
35,연령,61세 이상,364,14.2,36.7,5.7,10.8,5.9,8.2,1.4,5.7,4,3.8,3.6,4.07
36,방문목적,휴가 및 순수여행,5845,6.4,31.4,13.8,21.7,6.2,6.2,3.2,4.2,1.7,1.7,3.5,4.03
37,방문목적,비즈니스여행,194,46.4,19.7,12.4,7.7,2.5,2.5,0,2.9,0,1.3,4.6,2.87
38,방문목적,기타여행,94,54.4,25.9,7.9,5.4,1.2,2.5,2.3,0,0,0,0.3,2.04
39,여행형태,개별여행,5909,5.5,32,14.2,21.7,6.2,6.2,3.2,4.1,1.7,1.8,3.4,4.02
40,여행형태,패키지여행,203,88.7,2.5,0,1.2,0.1,1.2,0,1.2,0,0,5.1,2.19
41,여행형태,부분패키지여행,21,45.2,21.4,5.1,10.4,5.6,0,0,11.2,0,0,1.1,3.82
42,방문횟수,1회,1863,7.7,29.9,13.8,20.4,6.4,7.2,3.2,4.5,1.7,2.1,3.2,4.03
43,방문횟수,2회,2546,4.9,31.7,15,21.7,6.5,5.8,3,4,1.7,1.4,4.2,4.05
44,방문횟수,3회,830,10,31,11.9,22.2,5.5,5.4,4.9,3,1.6,1.7,2.9,3.95
45,방문횟수,4회 이상,894,18.3,31,11.4,19,4.6,4.5,1.1,4.2,1.6,1.8,2.5,3.58
46,♠BASE : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
expenditure_standard = expenditure_standard.drop(index = [0, 1]).reset_index(drop=True)

expenditure_standard

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,10명,11명 이상,평균
0,월별,01월,463,4.7,30.6,15,23.6,6.8,7.6,1.8,2.6,0.2,1.9,5.3,4.13
1,월별,02월,452,3.5,22.8,13.6,23.2,9.8,7.5,5.3,6,3.8,1.4,3.1,4.53
2,월별,03월,470,6.3,41.3,13.7,20.1,6.4,3.8,1.7,3.5,1,0.8,1.4,3.51
3,월별,04월,524,4.2,18.3,17.1,22,7.5,9.2,3.4,8.5,2.5,3,4.4,4.76
4,월별,05월,532,4.1,26.8,12.5,21.4,8.2,8.2,3.5,5.4,2.2,2.1,5.6,4.51
5,월별,06월,523,5.7,27.3,14,19.8,5.6,7.9,4.3,4.8,3.5,2.7,4.6,4.4
6,월별,07월,524,6.8,33.1,14.6,22,4.6,5.7,3.2,3.2,0.9,1.5,4.3,3.95
7,월별,08월,562,4.6,39.7,16.4,22.9,6.1,3.7,3.2,0.9,1.2,0.3,1,3.34
8,월별,09월,467,18.5,37,15.7,15.7,3.9,2,1.4,1.4,1.4,0.7,2.4,3.19
9,월별,10월,567,14.9,27,9.7,21.1,4.4,6.1,4.1,7.1,0,1.7,4,3.96
10,월별,11월,533,14.7,34.4,10.5,22.6,4.4,3.6,2.8,1.6,1.7,2.1,1.7,3.39
11,월별,12월,516,12.5,33.8,11.9,17.1,5.2,6.8,1.9,3.5,1.5,1.9,4,3.85
12,거주지,서울특별시,1422,9.5,33.3,14.6,20,6.2,4.9,3.2,3.5,1,1.2,2.6,3.67
13,거주지,부산광역시,576,6.4,30.4,10.4,26.9,6.4,6.3,2.9,3.9,1.2,1.6,3.7,4.02
14,거주지,대구광역시,369,6.4,29.5,17.6,19.8,4.9,5.7,2.9,6.2,1.6,2.3,3.1,4.06
15,거주지,인천광역시,390,7.6,28.7,17.2,24.2,4,7.9,2.1,3.4,0.9,1.8,2.2,3.74
16,거주지,광주광역시,168,11.5,27.5,8.8,16.3,10,8.9,3.6,2.8,4.9,3.7,1.9,4.21
17,거주지,대전광역시,184,10.2,32,10.9,18.5,6.3,4.4,2.6,7.7,0.8,2,4.7,4.17
18,거주지,울산광역시,187,1.2,25.9,7.9,26.8,8.6,12,4.7,4.9,0.6,1.4,6,4.72
19,거주지,세종자치시,76,6.5,29,10.9,21.3,3,14.2,1.5,6.3,3.1,0.5,3.7,4.27
20,거주지,경기도,1494,7.7,34.6,17,21.2,4.5,5.3,2.2,2.2,1.6,0.7,3,3.6
21,거주지,강원도,53,8.5,36.8,2.4,25.9,6.5,8.5,2.4,2.1,4.7,0,2.3,3.9
22,거주지,충청도,289,16.9,25.5,10.1,13.2,6.6,4.3,3.2,6.8,2.8,3.9,6.7,4.35
23,거주지,전라도,553,8,29,8.1,18.3,7.8,7.3,4.2,6.2,2.6,3.1,5.5,4.7
24,거주지,경상도,357,8.2,22,14.8,22.8,8.3,4.8,4.5,5.4,2.4,2.9,3.8,4.52
25,거주지,해외거주 등 기타 지역,16,15.5,32.2,1.2,6.6,15.1,7.3,15.5,6.6,0,0,0,3.9
26,성별,남자,2400,10.6,30.7,11.1,21.7,5.7,5.6,3.1,4.1,1.3,2,4,3.99
27,성별,여자,3733,7,31.1,15.3,20.5,6.3,6.3,3,4,1.8,1.5,3.2,3.94
28,연령,15세 - 20세,70,31.3,21,6.8,26.9,6.6,1.8,0,0,1.8,0,3.7,3.29
29,연령,21세 - 30세,1376,6.2,62,14.1,11.3,2.7,1.6,0.4,0.9,0.4,0.1,0.3,2.59
30,연령,31세 - 40세,1503,7.6,29.8,22.2,21.1,6,3.9,2.9,2.1,0.9,0.7,2.8,3.59
31,연령,41세 - 50세,1352,7.5,13.5,11.6,30.8,7.1,9.5,5.1,5.3,2.5,2.8,4.5,4.71
32,연령,51세 - 60세,1469,9.6,18.2,8.8,23.1,8.2,8.7,4.5,7.7,2.2,2.8,6.2,4.93
33,연령,61세 이상,364,14.2,36.7,5.7,10.8,5.9,8.2,1.4,5.7,4,3.8,3.6,4.07
34,방문목적,휴가 및 순수여행,5845,6.4,31.4,13.8,21.7,6.2,6.2,3.2,4.2,1.7,1.7,3.5,4.03
35,방문목적,비즈니스여행,194,46.4,19.7,12.4,7.7,2.5,2.5,0,2.9,0,1.3,4.6,2.87
36,방문목적,기타여행,94,54.4,25.9,7.9,5.4,1.2,2.5,2.3,0,0,0,0.3,2.04
37,여행형태,개별여행,5909,5.5,32,14.2,21.7,6.2,6.2,3.2,4.1,1.7,1.8,3.4,4.02
38,여행형태,패키지여행,203,88.7,2.5,0,1.2,0.1,1.2,0,1.2,0,0,5.1,2.19
39,여행형태,부분패키지여행,21,45.2,21.4,5.1,10.4,5.6,0,0,11.2,0,0,1.1,3.82
40,방문횟수,1회,1863,7.7,29.9,13.8,20.4,6.4,7.2,3.2,4.5,1.7,2.1,3.2,4.03
41,방문횟수,2회,2546,4.9,31.7,15,21.7,6.5,5.8,3,4,1.7,1.4,4.2,4.05
42,방문횟수,3회,830,10,31,11.9,22.2,5.5,5.4,4.9,3,1.6,1.7,2.9,3.95
43,방문횟수,4회 이상,894,18.3,31,11.4,19,4.6,4.5,1.1,4.2,1.6,1.8,2.5,3.58
44,♠BASE : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
expenditure_standard = expenditure_standard.drop(index = range(12, 28)).reset_index(drop=True)

expenditure_standard

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,10명,11명 이상,평균
0,월별,01월,463,4.7,30.6,15,23.6,6.8,7.6,1.8,2.6,0.2,1.9,5.3,4.13
1,월별,02월,452,3.5,22.8,13.6,23.2,9.8,7.5,5.3,6,3.8,1.4,3.1,4.53
2,월별,03월,470,6.3,41.3,13.7,20.1,6.4,3.8,1.7,3.5,1,0.8,1.4,3.51
3,월별,04월,524,4.2,18.3,17.1,22,7.5,9.2,3.4,8.5,2.5,3,4.4,4.76
4,월별,05월,532,4.1,26.8,12.5,21.4,8.2,8.2,3.5,5.4,2.2,2.1,5.6,4.51
5,월별,06월,523,5.7,27.3,14,19.8,5.6,7.9,4.3,4.8,3.5,2.7,4.6,4.4
6,월별,07월,524,6.8,33.1,14.6,22,4.6,5.7,3.2,3.2,0.9,1.5,4.3,3.95
7,월별,08월,562,4.6,39.7,16.4,22.9,6.1,3.7,3.2,0.9,1.2,0.3,1,3.34
8,월별,09월,467,18.5,37,15.7,15.7,3.9,2,1.4,1.4,1.4,0.7,2.4,3.19
9,월별,10월,567,14.9,27,9.7,21.1,4.4,6.1,4.1,7.1,0,1.7,4,3.96
10,월별,11월,533,14.7,34.4,10.5,22.6,4.4,3.6,2.8,1.6,1.7,2.1,1.7,3.39
11,월별,12월,516,12.5,33.8,11.9,17.1,5.2,6.8,1.9,3.5,1.5,1.9,4,3.85
12,연령,15세 - 20세,70,31.3,21,6.8,26.9,6.6,1.8,0,0,1.8,0,3.7,3.29
13,연령,21세 - 30세,1376,6.2,62,14.1,11.3,2.7,1.6,0.4,0.9,0.4,0.1,0.3,2.59
14,연령,31세 - 40세,1503,7.6,29.8,22.2,21.1,6,3.9,2.9,2.1,0.9,0.7,2.8,3.59
15,연령,41세 - 50세,1352,7.5,13.5,11.6,30.8,7.1,9.5,5.1,5.3,2.5,2.8,4.5,4.71
16,연령,51세 - 60세,1469,9.6,18.2,8.8,23.1,8.2,8.7,4.5,7.7,2.2,2.8,6.2,4.93
17,연령,61세 이상,364,14.2,36.7,5.7,10.8,5.9,8.2,1.4,5.7,4,3.8,3.6,4.07
18,방문목적,휴가 및 순수여행,5845,6.4,31.4,13.8,21.7,6.2,6.2,3.2,4.2,1.7,1.7,3.5,4.03
19,방문목적,비즈니스여행,194,46.4,19.7,12.4,7.7,2.5,2.5,0,2.9,0,1.3,4.6,2.87
20,방문목적,기타여행,94,54.4,25.9,7.9,5.4,1.2,2.5,2.3,0,0,0,0.3,2.04
21,여행형태,개별여행,5909,5.5,32,14.2,21.7,6.2,6.2,3.2,4.1,1.7,1.8,3.4,4.02
22,여행형태,패키지여행,203,88.7,2.5,0,1.2,0.1,1.2,0,1.2,0,0,5.1,2.19
23,여행형태,부분패키지여행,21,45.2,21.4,5.1,10.4,5.6,0,0,11.2,0,0,1.1,3.82
24,방문횟수,1회,1863,7.7,29.9,13.8,20.4,6.4,7.2,3.2,4.5,1.7,2.1,3.2,4.03
25,방문횟수,2회,2546,4.9,31.7,15,21.7,6.5,5.8,3,4,1.7,1.4,4.2,4.05
26,방문횟수,3회,830,10,31,11.9,22.2,5.5,5.4,4.9,3,1.6,1.7,2.9,3.95
27,방문횟수,4회 이상,894,18.3,31,11.4,19,4.6,4.5,1.1,4.2,1.6,1.8,2.5,3.58
28,♠BASE : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 전처리가 완료된 지출 기준인원.
  + 의도한 것은 아니지만, 2명의 비율이 가장 높고 9, 10명의 비율이 거의 없는 수치에 가까운 결과를 보아 층화추출이 적용된 것으로 확인된다.

In [100]:
expenditure_standard = expenditure_standard.drop(index = range(18, 29)).reset_index(drop=True)

expenditure_standard

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,10명,11명 이상,평균
0,월별,01월,463,4.7,30.6,15,23.6,6.8,7.6,1.8,2.6,0.2,1.9,5.3,4.13
1,월별,02월,452,3.5,22.8,13.6,23.2,9.8,7.5,5.3,6,3.8,1.4,3.1,4.53
2,월별,03월,470,6.3,41.3,13.7,20.1,6.4,3.8,1.7,3.5,1,0.8,1.4,3.51
3,월별,04월,524,4.2,18.3,17.1,22,7.5,9.2,3.4,8.5,2.5,3,4.4,4.76
4,월별,05월,532,4.1,26.8,12.5,21.4,8.2,8.2,3.5,5.4,2.2,2.1,5.6,4.51
5,월별,06월,523,5.7,27.3,14,19.8,5.6,7.9,4.3,4.8,3.5,2.7,4.6,4.4
6,월별,07월,524,6.8,33.1,14.6,22,4.6,5.7,3.2,3.2,0.9,1.5,4.3,3.95
7,월별,08월,562,4.6,39.7,16.4,22.9,6.1,3.7,3.2,0.9,1.2,0.3,1,3.34
8,월별,09월,467,18.5,37,15.7,15.7,3.9,2,1.4,1.4,1.4,0.7,2.4,3.19
9,월별,10월,567,14.9,27,9.7,21.1,4.4,6.1,4.1,7.1,0,1.7,4,3.96
10,월별,11월,533,14.7,34.4,10.5,22.6,4.4,3.6,2.8,1.6,1.7,2.1,1.7,3.39
11,월별,12월,516,12.5,33.8,11.9,17.1,5.2,6.8,1.9,3.5,1.5,1.9,4,3.85
12,연령,15세 - 20세,70,31.3,21,6.8,26.9,6.6,1.8,0,0,1.8,0,3.7,3.29
13,연령,21세 - 30세,1376,6.2,62,14.1,11.3,2.7,1.6,0.4,0.9,0.4,0.1,0.3,2.59
14,연령,31세 - 40세,1503,7.6,29.8,22.2,21.1,6,3.9,2.9,2.1,0.9,0.7,2.8,3.59
15,연령,41세 - 50세,1352,7.5,13.5,11.6,30.8,7.1,9.5,5.1,5.3,2.5,2.8,4.5,4.71
16,연령,51세 - 60세,1469,9.6,18.2,8.8,23.1,8.2,8.7,4.5,7.7,2.2,2.8,6.2,4.93
17,연령,61세 이상,364,14.2,36.7,5.7,10.8,5.9,8.2,1.4,5.7,4,3.8,3.6,4.07

#### 1인당 지출 경비 - 전체 비용
- 해당 파일에 대한 전처리

In [101]:
total_cost = pd.read_excel(DATA_path + '2019년 1인당 지출경비 - 개별 전체.xlsx')
total_cost

,table,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,사례수,10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,100만원 이상-150만원 미만,150만원 이상,[평균]
1,[전체],NaN,5909,0,14.8,55.7,26.7,2.3,0.5,463530.97
2,월별,01월,459,0,28,54.5,16.2,0.6,0.6,398538.07
3,월별,02월,447,0,9.6,55.4,33.4,1.1,0.6,487232.82
4,월별,03월,464,0,25.4,51.3,20.2,2.5,0.6,445378.82
5,월별,04월,508,0,16.1,66,16.1,1.3,0.4,422618.93
6,월별,05월,523,0,8.9,56.2,31.9,2.7,0.2,487010.1
7,월별,06월,505,0,7.1,56.6,33.2,3.1,0,478963.07
8,월별,07월,501,0,13,56,28.8,2,0.3,465747.87
9,월별,08월,552,0,9.9,50,36.8,2.7,0.6,511081.46
10,월별,09월,434,0.2,23.8,48.4,24.2,2.4,0.9,446911.82
11,월별,10월,522,0,12,56.5,28.3,2.6,0.6,475645.81
12,월별,11월,504,0,15.8,57.8,22.5,3.6,0.3,458333.05
13,월별,12월,490,0.3,10.9,58.5,26.7,3.1,0.5,472795.14
14,거주지,서울특별시,1386,0,15.8,52.9,28.4,2.7,0.3,469231.65
15,거주지,부산광역시,565,0,9.2,54.3,32.5,3,1.1,502689.53
16,거주지,대구광역시,363,0,11.4,59.3,28.6,0.7,0.1,442913.5
17,거주지,인천광역시,378,0,18.4,60.9,18.7,2,0.1,425577.46
18,거주지,광주광역시,159,0,16.1,46.9,29.6,6.8,0.7,520481.55
19,거주지,대전광역시,173,0,16,56.3,25.3,2.1,0.3,456699.07
20,거주지,울산광역시,182,0,9.4,61.6,24,4.8,0.2,480234.69
21,거주지,세종자치시,72,0,9.5,55.7,33.1,1.7,0,465859.74
22,거주지,경기도,1452,0.1,16.6,57.2,24.2,1.3,0.7,448696.91
23,거주지,강원도,49,0,6.8,54.8,28.9,7,2.6,577273.36
24,거주지,충청도,248,0,11.6,53.9,31,3,0.5,479300.54
25,거주지,전라도,522,0,17.4,56.5,23.4,2.5,0.2,442298.75
26,거주지,경상도,343,0.4,13.7,55.7,27.9,1.7,0.6,470055.73
27,거주지,해외거주 등 기타 지역,15,0,16.8,24,49.5,8.4,1.3,566239.04
28,성별,남자,2305,0.1,16.2,50.5,29.5,3.2,0.5,480890.98
29,성별,여자,3604,0,13.8,59,24.9,1.7,0.4,452428.71
30,연령,15세 - 20세,49,0,13.2,57.3,29.5,0,0,447993.61
31,연령,21세 - 30세,1371,0.1,19.5,61.9,17.6,0.8,0.1,410131.26
32,연령,31세 - 40세,1478,0,15.6,54.2,27.5,2.2,0.6,461050.31
33,연령,41세 - 50세,1314,0,13.3,59.1,24.9,2.3,0.4,463837.02
34,연령,51세 - 60세,1375,0.1,10.4,51.4,33.3,4.1,0.8,511537.45
35,연령,61세 이상,323,0,15.6,40.1,41.2,2.6,0.5,498257.07
36,방문목적,휴가 및 순수여행,5659,0,14.1,56.3,26.8,2.3,0.4,463592.25
37,방문목적,비즈니스여행,167,0,31.6,43.8,19.8,3.6,1.2,451789.91
38,방문목적,기타여행,84,0,23.9,38.6,34,2.8,0.7,482793.89
39,여행형태,개별여행,5909,0,14.8,55.7,26.7,2.3,0.5,463530.97
40,방문횟수,1회,1786,0,13.9,59.3,25.2,1.2,0.4,447727.96
41,방문횟수,2회,2476,0,14.3,58,25.8,1.6,0.4,452207.14
42,방문횟수,3회,794,0.2,14.5,53.6,27.4,3.8,0.5,485925.29
43,방문횟수,4회 이상,854,0.1,18.2,43.6,32,5.4,0.7,508601.9
44,♠BASE : 13번의 1번 응답자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '10만원 미만',
           'Unnamed: 4' : '10만원 이상-30만원 미만',
           'Unnamed: 5' : '30만원 이상-50만원 미만',
           'Unnamed: 6' : '50만원 이상-100만원 미만',
           'Unnamed: 7' : '100만원 이상-150만원 미만',
           'Unnamed: 8' : '150만원 이상',
           'Unnamed: 9' : '평균'}

total_cost = total_cost.rename(columns = columns)
total_cost

,분석 카테고리,세부 카테고리,사례수,10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,100만원 이상-150만원 미만,150만원 이상,평균
0,NaN,NaN,사례수,10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,100만원 이상-150만원 미만,150만원 이상,[평균]
1,[전체],NaN,5909,0,14.8,55.7,26.7,2.3,0.5,463530.97
2,월별,01월,459,0,28,54.5,16.2,0.6,0.6,398538.07
3,월별,02월,447,0,9.6,55.4,33.4,1.1,0.6,487232.82
4,월별,03월,464,0,25.4,51.3,20.2,2.5,0.6,445378.82
5,월별,04월,508,0,16.1,66,16.1,1.3,0.4,422618.93
6,월별,05월,523,0,8.9,56.2,31.9,2.7,0.2,487010.1
7,월별,06월,505,0,7.1,56.6,33.2,3.1,0,478963.07
8,월별,07월,501,0,13,56,28.8,2,0.3,465747.87
9,월별,08월,552,0,9.9,50,36.8,2.7,0.6,511081.46
10,월별,09월,434,0.2,23.8,48.4,24.2,2.4,0.9,446911.82
11,월별,10월,522,0,12,56.5,28.3,2.6,0.6,475645.81
12,월별,11월,504,0,15.8,57.8,22.5,3.6,0.3,458333.05
13,월별,12월,490,0.3,10.9,58.5,26.7,3.1,0.5,472795.14
14,거주지,서울특별시,1386,0,15.8,52.9,28.4,2.7,0.3,469231.65
15,거주지,부산광역시,565,0,9.2,54.3,32.5,3,1.1,502689.53
16,거주지,대구광역시,363,0,11.4,59.3,28.6,0.7,0.1,442913.5
17,거주지,인천광역시,378,0,18.4,60.9,18.7,2,0.1,425577.46
18,거주지,광주광역시,159,0,16.1,46.9,29.6,6.8,0.7,520481.55
19,거주지,대전광역시,173,0,16,56.3,25.3,2.1,0.3,456699.07
20,거주지,울산광역시,182,0,9.4,61.6,24,4.8,0.2,480234.69
21,거주지,세종자치시,72,0,9.5,55.7,33.1,1.7,0,465859.74
22,거주지,경기도,1452,0.1,16.6,57.2,24.2,1.3,0.7,448696.91
23,거주지,강원도,49,0,6.8,54.8,28.9,7,2.6,577273.36
24,거주지,충청도,248,0,11.6,53.9,31,3,0.5,479300.54
25,거주지,전라도,522,0,17.4,56.5,23.4,2.5,0.2,442298.75
26,거주지,경상도,343,0.4,13.7,55.7,27.9,1.7,0.6,470055.73
27,거주지,해외거주 등 기타 지역,15,0,16.8,24,49.5,8.4,1.3,566239.04
28,성별,남자,2305,0.1,16.2,50.5,29.5,3.2,0.5,480890.98
29,성별,여자,3604,0,13.8,59,24.9,1.7,0.4,452428.71
30,연령,15세 - 20세,49,0,13.2,57.3,29.5,0,0,447993.61
31,연령,21세 - 30세,1371,0.1,19.5,61.9,17.6,0.8,0.1,410131.26
32,연령,31세 - 40세,1478,0,15.6,54.2,27.5,2.2,0.6,461050.31
33,연령,41세 - 50세,1314,0,13.3,59.1,24.9,2.3,0.4,463837.02
34,연령,51세 - 60세,1375,0.1,10.4,51.4,33.3,4.1,0.8,511537.45
35,연령,61세 이상,323,0,15.6,40.1,41.2,2.6,0.5,498257.07
36,방문목적,휴가 및 순수여행,5659,0,14.1,56.3,26.8,2.3,0.4,463592.25
37,방문목적,비즈니스여행,167,0,31.6,43.8,19.8,3.6,1.2,451789.91
38,방문목적,기타여행,84,0,23.9,38.6,34,2.8,0.7,482793.89
39,여행형태,개별여행,5909,0,14.8,55.7,26.7,2.3,0.5,463530.97
40,방문횟수,1회,1786,0,13.9,59.3,25.2,1.2,0.4,447727.96
41,방문횟수,2회,2476,0,14.3,58,25.8,1.6,0.4,452207.14
42,방문횟수,3회,794,0.2,14.5,53.6,27.4,3.8,0.5,485925.29
43,방문횟수,4회 이상,854,0.1,18.2,43.6,32,5.4,0.7,508601.9
44,♠BASE : 13번의 1번 응답자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
total_cost = total_cost.drop(index = [0, 1]).reset_index(drop=True)

total_cost

,분석 카테고리,세부 카테고리,사례수,10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,100만원 이상-150만원 미만,150만원 이상,평균
0,월별,01월,459,0,28,54.5,16.2,0.6,0.6,398538.07
1,월별,02월,447,0,9.6,55.4,33.4,1.1,0.6,487232.82
2,월별,03월,464,0,25.4,51.3,20.2,2.5,0.6,445378.82
3,월별,04월,508,0,16.1,66,16.1,1.3,0.4,422618.93
4,월별,05월,523,0,8.9,56.2,31.9,2.7,0.2,487010.1
5,월별,06월,505,0,7.1,56.6,33.2,3.1,0,478963.07
6,월별,07월,501,0,13,56,28.8,2,0.3,465747.87
7,월별,08월,552,0,9.9,50,36.8,2.7,0.6,511081.46
8,월별,09월,434,0.2,23.8,48.4,24.2,2.4,0.9,446911.82
9,월별,10월,522,0,12,56.5,28.3,2.6,0.6,475645.81
10,월별,11월,504,0,15.8,57.8,22.5,3.6,0.3,458333.05
11,월별,12월,490,0.3,10.9,58.5,26.7,3.1,0.5,472795.14
12,거주지,서울특별시,1386,0,15.8,52.9,28.4,2.7,0.3,469231.65
13,거주지,부산광역시,565,0,9.2,54.3,32.5,3,1.1,502689.53
14,거주지,대구광역시,363,0,11.4,59.3,28.6,0.7,0.1,442913.5
15,거주지,인천광역시,378,0,18.4,60.9,18.7,2,0.1,425577.46
16,거주지,광주광역시,159,0,16.1,46.9,29.6,6.8,0.7,520481.55
17,거주지,대전광역시,173,0,16,56.3,25.3,2.1,0.3,456699.07
18,거주지,울산광역시,182,0,9.4,61.6,24,4.8,0.2,480234.69
19,거주지,세종자치시,72,0,9.5,55.7,33.1,1.7,0,465859.74
20,거주지,경기도,1452,0.1,16.6,57.2,24.2,1.3,0.7,448696.91
21,거주지,강원도,49,0,6.8,54.8,28.9,7,2.6,577273.36
22,거주지,충청도,248,0,11.6,53.9,31,3,0.5,479300.54
23,거주지,전라도,522,0,17.4,56.5,23.4,2.5,0.2,442298.75
24,거주지,경상도,343,0.4,13.7,55.7,27.9,1.7,0.6,470055.73
25,거주지,해외거주 등 기타 지역,15,0,16.8,24,49.5,8.4,1.3,566239.04
26,성별,남자,2305,0.1,16.2,50.5,29.5,3.2,0.5,480890.98
27,성별,여자,3604,0,13.8,59,24.9,1.7,0.4,452428.71
28,연령,15세 - 20세,49,0,13.2,57.3,29.5,0,0,447993.61
29,연령,21세 - 30세,1371,0.1,19.5,61.9,17.6,0.8,0.1,410131.26
30,연령,31세 - 40세,1478,0,15.6,54.2,27.5,2.2,0.6,461050.31
31,연령,41세 - 50세,1314,0,13.3,59.1,24.9,2.3,0.4,463837.02
32,연령,51세 - 60세,1375,0.1,10.4,51.4,33.3,4.1,0.8,511537.45
33,연령,61세 이상,323,0,15.6,40.1,41.2,2.6,0.5,498257.07
34,방문목적,휴가 및 순수여행,5659,0,14.1,56.3,26.8,2.3,0.4,463592.25
35,방문목적,비즈니스여행,167,0,31.6,43.8,19.8,3.6,1.2,451789.91
36,방문목적,기타여행,84,0,23.9,38.6,34,2.8,0.7,482793.89
37,여행형태,개별여행,5909,0,14.8,55.7,26.7,2.3,0.5,463530.97
38,방문횟수,1회,1786,0,13.9,59.3,25.2,1.2,0.4,447727.96
39,방문횟수,2회,2476,0,14.3,58,25.8,1.6,0.4,452207.14
40,방문횟수,3회,794,0.2,14.5,53.6,27.4,3.8,0.5,485925.29
41,방문횟수,4회 이상,854,0.1,18.2,43.6,32,5.4,0.7,508601.9
42,♠BASE : 13번의 1번 응답자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
total_cost = total_cost.drop(index = range(12, 28)).reset_index(drop=True)

total_cost

,분석 카테고리,세부 카테고리,사례수,10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,100만원 이상-150만원 미만,150만원 이상,평균
0,월별,01월,459,0,28,54.5,16.2,0.6,0.6,398538.07
1,월별,02월,447,0,9.6,55.4,33.4,1.1,0.6,487232.82
2,월별,03월,464,0,25.4,51.3,20.2,2.5,0.6,445378.82
3,월별,04월,508,0,16.1,66,16.1,1.3,0.4,422618.93
4,월별,05월,523,0,8.9,56.2,31.9,2.7,0.2,487010.1
5,월별,06월,505,0,7.1,56.6,33.2,3.1,0,478963.07
6,월별,07월,501,0,13,56,28.8,2,0.3,465747.87
7,월별,08월,552,0,9.9,50,36.8,2.7,0.6,511081.46
8,월별,09월,434,0.2,23.8,48.4,24.2,2.4,0.9,446911.82
9,월별,10월,522,0,12,56.5,28.3,2.6,0.6,475645.81
10,월별,11월,504,0,15.8,57.8,22.5,3.6,0.3,458333.05
11,월별,12월,490,0.3,10.9,58.5,26.7,3.1,0.5,472795.14
12,연령,15세 - 20세,49,0,13.2,57.3,29.5,0,0,447993.61
13,연령,21세 - 30세,1371,0.1,19.5,61.9,17.6,0.8,0.1,410131.26
14,연령,31세 - 40세,1478,0,15.6,54.2,27.5,2.2,0.6,461050.31
15,연령,41세 - 50세,1314,0,13.3,59.1,24.9,2.3,0.4,463837.02
16,연령,51세 - 60세,1375,0.1,10.4,51.4,33.3,4.1,0.8,511537.45
17,연령,61세 이상,323,0,15.6,40.1,41.2,2.6,0.5,498257.07
18,방문목적,휴가 및 순수여행,5659,0,14.1,56.3,26.8,2.3,0.4,463592.25
19,방문목적,비즈니스여행,167,0,31.6,43.8,19.8,3.6,1.2,451789.91
20,방문목적,기타여행,84,0,23.9,38.6,34,2.8,0.7,482793.89
21,여행형태,개별여행,5909,0,14.8,55.7,26.7,2.3,0.5,463530.97
22,방문횟수,1회,1786,0,13.9,59.3,25.2,1.2,0.4,447727.96
23,방문횟수,2회,2476,0,14.3,58,25.8,1.6,0.4,452207.14
24,방문횟수,3회,794,0.2,14.5,53.6,27.4,3.8,0.5,485925.29
25,방문횟수,4회 이상,854,0.1,18.2,43.6,32,5.4,0.7,508601.9
26,♠BASE : 13번의 1번 응답자,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 전처리가 완료된 전체 비용에 대한 1인당 지출 경비.
  + 의도한 것은 아니지만, 30만원 이상-50만원 미만의 비율이 가장 높은 결과를 보아 층화추출이 적용된 것으로 확인된다.

In [105]:
total_cost = total_cost.drop(index = range(18, 27)).reset_index(drop=True)

total_cost

,분석 카테고리,세부 카테고리,사례수,10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,100만원 이상-150만원 미만,150만원 이상,평균
0,월별,01월,459,0,28,54.5,16.2,0.6,0.6,398538.07
1,월별,02월,447,0,9.6,55.4,33.4,1.1,0.6,487232.82
2,월별,03월,464,0,25.4,51.3,20.2,2.5,0.6,445378.82
3,월별,04월,508,0,16.1,66,16.1,1.3,0.4,422618.93
4,월별,05월,523,0,8.9,56.2,31.9,2.7,0.2,487010.1
5,월별,06월,505,0,7.1,56.6,33.2,3.1,0,478963.07
6,월별,07월,501,0,13,56,28.8,2,0.3,465747.87
7,월별,08월,552,0,9.9,50,36.8,2.7,0.6,511081.46
8,월별,09월,434,0.2,23.8,48.4,24.2,2.4,0.9,446911.82
9,월별,10월,522,0,12,56.5,28.3,2.6,0.6,475645.81
10,월별,11월,504,0,15.8,57.8,22.5,3.6,0.3,458333.05
11,월별,12월,490,0.3,10.9,58.5,26.7,3.1,0.5,472795.14
12,연령,15세 - 20세,49,0,13.2,57.3,29.5,0,0,447993.61
13,연령,21세 - 30세,1371,0.1,19.5,61.9,17.6,0.8,0.1,410131.26
14,연령,31세 - 40세,1478,0,15.6,54.2,27.5,2.2,0.6,461050.31
15,연령,41세 - 50세,1314,0,13.3,59.1,24.9,2.3,0.4,463837.02
16,연령,51세 - 60세,1375,0.1,10.4,51.4,33.3,4.1,0.8,511537.45
17,연령,61세 이상,323,0,15.6,40.1,41.2,2.6,0.5,498257.07