# 2022년

## 데이터 전처리

### 데이터 수집 비율
- 2022년도 여름 시즌 제주 여행자를 대상으로 한 방문 관광객 실태조사에서 응답자 프로파일을 가져옴.
  + 응답자 프로파일의 카테고리 중 월별 카테고리만 수집함.
- **해당 연도의 데이터 수집 대상 비율을 명시해 앞으로 다룰 데이터들이 어떤 방식으로 추출되었는지 설명함.**

In [7]:
import pandas as pd

DATA_path = '/content/drive/MyDrive/세프/DATA/'

profile_df_2022 = pd.read_excel(DATA_path + '2022년 제주방문 응답자 프로파일 - 데이터 설명용.xlsx')
profile_df_2022.head()

  table Unnamed: 1 Unnamed: 2
0   NaN        NaN         전체
1   NaN        NaN        사례수
2    전체        NaN        629
3    권역     서울/경인권        420
4    권역        경상권        114

In [9]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수'}

profile_df_2022 = profile_df_2022.rename(columns = columns)
profile_df_2022.head()

  분석 카테고리 세부 카테고리  사례수
0     NaN     NaN   전체
1     NaN     NaN  사례수
2      전체     NaN  629
3      권역  서울/경인권  420
4      권역     경상권  114

In [10]:
profile_df_2022 = profile_df_2022.drop(index = [0, 1, 2]).reset_index(drop=True)
profile_df_2022

      분석 카테고리    세부 카테고리  사례수
0          권역     서울/경인권  420
1          권역        경상권  114
2          권역        호남권   42
3          권역     충청/강원권   53
4          성별         남자  366
5          성별         여자  263
6          연령     15~20세   13
7          연령     21~30세  108
8          연령     31~40세  200
9          연령     41~50세  176
10         연령     51~60세   92
11         연령     61세 이상   40
12         직업         학생   30
13         직업     사무/전문직  442
14         직업     판매/기술직   66
15         직업        자영업   31
16         직업       전업주부   38
17         직업   기타(무직 등)   22
18  월 평균 가구소득   400만원 미만   98
19  월 평균 가구소득  400-599만원  200
20  월 평균 가구소득  600-799만원  154
21  월 평균 가구소득   800만원 이상  177
22       거주지역      서울특별시  297
23       거주지역      부산광역시   52
24       거주지역      대구광역시   28
25       거주지역      인천광역시   33
26       거주지역      광주광역시   24
27       거주지역      대전광역시   24
28       거주지역      울산광역시   15
29       거주지역    세종특별자치도    1
30       거주지역        경기도   90
31       거주지역        강원도    8
32       거주지역        충청도   20
33       거주지역        전라도   18
34       거주지역        경상도   19

### 1인당 지출 경비 전처리
- 1인당 지출 경비에 대한 카테고리 : 숙박 부분, 식음료 부분, 관광지 이용료 부분
- **1인당 지출 경비 부분이 지출 기준인원 항목의 하위 항목으로 분류되어 있어 응답자 프로파일처럼 해당 데이터의 비율을 명시함.**

In [6]:
expenditure_standard_2022 = pd.read_excel(DATA_path + '2022년 지출 기준인원 - 1인당 지출 경비에 대한 상위 항목.xlsx')
expenditure_standard_2022

,table,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균(명)
1,전체,NaN,629,7.8,32.4,25,28.1,4.9,1.1,0.2,0.3,0.2,3
2,권역,서울/경인권,420,7.6,34.5,27.6,23.8,4,1.7,0.2,0.5,0,2.9
3,권역,경상권,114,9.6,32.5,16.7,35.1,5.3,0,0,0,0.9,3
4,권역,호남권,42,9.5,23.8,23.8,33.3,9.5,0,0,0,0,3.1
5,권역,충청/강원권,53,3.8,22.6,22.6,43.4,7.5,0,0,0,0,3.3
6,성별,남자,366,9.8,29.8,25.1,28.7,4.4,1.4,0.3,0.3,0.3,3
7,성별,여자,263,4.9,36.1,24.7,27.4,5.7,0.8,0,0.4,0,3
8,연령,15~20세,13,0,30.8,30.8,38.5,0,0,0,0,0,3.1
9,연령,21~30세,108,13,48.1,15.7,17.6,3.7,0.9,0,0.9,0,2.6
10,연령,31~40세,200,7.5,31,30,26.5,3.5,1,0.5,0,0,2.9
11,연령,41~50세,176,4.5,18.2,27.8,40.9,6.2,1.1,0,0.6,0.6,3.4
12,연령,51~60세,92,9.8,34.8,25,21.7,7.6,1.1,0,0,0,2.9
13,연령,61세 이상,40,7.5,55,10,20,5,2.5,0,0,0,2.7
14,직업,학생,30,10,30,26.7,26.7,3.3,3.3,0,0,0,2.9
15,직업,사무/전문직,442,7.9,32.1,24.2,28.5,5.7,0.9,0.2,0.2,0.2,3
16,직업,판매/기술직,66,7.6,25.8,34.8,27.3,3,0,0,1.5,0,3
17,직업,자영업,31,3.2,38.7,22.6,32.3,0,3.2,0,0,0,3
18,직업,전업주부,38,5.3,31.6,28.9,26.3,7.9,0,0,0,0,3
19,직업,기타(무직 등),22,13.6,54.5,4.5,22.7,0,4.5,0,0,0,2.5
20,월 평균 가구소득,400만원 미만,98,11.2,46.9,21.4,19.4,1,0,0,0,0,2.5
21,월 평균 가구소득,400-599만원,200,7.5,27.5,27.5,31.5,4.5,1,0,0.5,0,3
22,월 평균 가구소득,600-799만원,154,8.4,27.3,24,33.1,3.9,2.6,0.6,0,0,3.1
23,월 평균 가구소득,800만원 이상,177,5.6,34.5,24.9,24.9,8.5,0.6,0,0.6,0.6,3
24,거주지역,서울특별시,297,7.7,36,29.3,20.2,4.7,1,0.3,0.7,0,2.9
25,거주지역,부산광역시,52,5.8,46.2,9.6,30.8,5.8,0,0,0,1.9,3
26,거주지역,대구광역시,28,10.7,25,17.9,42.9,3.6,0,0,0,0,3
27,거주지역,인천광역시,33,3,33.3,15.2,36.4,3,9.1,0,0,0,3.3
28,거주지역,광주광역시,24,16.7,25,12.5,37.5,8.3,0,0,0,0,3
29,거주지역,대전광역시,24,4.2,29.2,20.8,37.5,8.3,0,0,0,0,3.2
30,거주지역,울산광역시,15,6.7,26.7,26.7,40,0,0,0,0,0,3
31,거주지역,세종특별자치도,1,0,0,0,0,100,0,0,0,0,5
32,거주지역,경기도,90,8.9,30,26.7,31.1,2.2,1.1,0,0,0,2.9
33,거주지역,강원도,8,0,12.5,37.5,37.5,12.5,0,0,0,0,3.5
34,거주지역,충청도,20,5,20,20,55,0,0,0,0,0,3.2
35,거주지역,전라도,18,0,22.2,38.9,27.8,11.1,0,0,0,0,3.3
36,거주지역,경상도,19,21.1,10.5,26.3,31.6,10.5,0,0,0,0,3
37,BASE : 제주여행 방문자(SQ1=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '1명',
           'Unnamed: 4' : '2명',
           'Unnamed: 5' : '3명',
           'Unnamed: 6' : '4명',
           'Unnamed: 7' : '5명',
           'Unnamed: 8' : '6명',
           'Unnamed: 9' : '7명',
           'Unnamed: 10' : '8명',
           'Unnamed: 11' : '9명',
           'Unnamed: 12' : '평균'}

expenditure_standard_2022 = expenditure_standard_2022.rename(columns = columns)
expenditure_standard_2022

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균
0,NaN,NaN,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균(명)
1,전체,NaN,629,7.8,32.4,25,28.1,4.9,1.1,0.2,0.3,0.2,3
2,권역,서울/경인권,420,7.6,34.5,27.6,23.8,4,1.7,0.2,0.5,0,2.9
3,권역,경상권,114,9.6,32.5,16.7,35.1,5.3,0,0,0,0.9,3
4,권역,호남권,42,9.5,23.8,23.8,33.3,9.5,0,0,0,0,3.1
5,권역,충청/강원권,53,3.8,22.6,22.6,43.4,7.5,0,0,0,0,3.3
6,성별,남자,366,9.8,29.8,25.1,28.7,4.4,1.4,0.3,0.3,0.3,3
7,성별,여자,263,4.9,36.1,24.7,27.4,5.7,0.8,0,0.4,0,3
8,연령,15~20세,13,0,30.8,30.8,38.5,0,0,0,0,0,3.1
9,연령,21~30세,108,13,48.1,15.7,17.6,3.7,0.9,0,0.9,0,2.6
10,연령,31~40세,200,7.5,31,30,26.5,3.5,1,0.5,0,0,2.9
11,연령,41~50세,176,4.5,18.2,27.8,40.9,6.2,1.1,0,0.6,0.6,3.4
12,연령,51~60세,92,9.8,34.8,25,21.7,7.6,1.1,0,0,0,2.9
13,연령,61세 이상,40,7.5,55,10,20,5,2.5,0,0,0,2.7
14,직업,학생,30,10,30,26.7,26.7,3.3,3.3,0,0,0,2.9
15,직업,사무/전문직,442,7.9,32.1,24.2,28.5,5.7,0.9,0.2,0.2,0.2,3
16,직업,판매/기술직,66,7.6,25.8,34.8,27.3,3,0,0,1.5,0,3
17,직업,자영업,31,3.2,38.7,22.6,32.3,0,3.2,0,0,0,3
18,직업,전업주부,38,5.3,31.6,28.9,26.3,7.9,0,0,0,0,3
19,직업,기타(무직 등),22,13.6,54.5,4.5,22.7,0,4.5,0,0,0,2.5
20,월 평균 가구소득,400만원 미만,98,11.2,46.9,21.4,19.4,1,0,0,0,0,2.5
21,월 평균 가구소득,400-599만원,200,7.5,27.5,27.5,31.5,4.5,1,0,0.5,0,3
22,월 평균 가구소득,600-799만원,154,8.4,27.3,24,33.1,3.9,2.6,0.6,0,0,3.1
23,월 평균 가구소득,800만원 이상,177,5.6,34.5,24.9,24.9,8.5,0.6,0,0.6,0.6,3
24,거주지역,서울특별시,297,7.7,36,29.3,20.2,4.7,1,0.3,0.7,0,2.9
25,거주지역,부산광역시,52,5.8,46.2,9.6,30.8,5.8,0,0,0,1.9,3
26,거주지역,대구광역시,28,10.7,25,17.9,42.9,3.6,0,0,0,0,3
27,거주지역,인천광역시,33,3,33.3,15.2,36.4,3,9.1,0,0,0,3.3
28,거주지역,광주광역시,24,16.7,25,12.5,37.5,8.3,0,0,0,0,3
29,거주지역,대전광역시,24,4.2,29.2,20.8,37.5,8.3,0,0,0,0,3.2
30,거주지역,울산광역시,15,6.7,26.7,26.7,40,0,0,0,0,0,3
31,거주지역,세종특별자치도,1,0,0,0,0,100,0,0,0,0,5
32,거주지역,경기도,90,8.9,30,26.7,31.1,2.2,1.1,0,0,0,2.9
33,거주지역,강원도,8,0,12.5,37.5,37.5,12.5,0,0,0,0,3.5
34,거주지역,충청도,20,5,20,20,55,0,0,0,0,0,3.2
35,거주지역,전라도,18,0,22.2,38.9,27.8,11.1,0,0,0,0,3.3
36,거주지역,경상도,19,21.1,10.5,26.3,31.6,10.5,0,0,0,0,3
37,BASE : 제주여행 방문자(SQ1=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 1인당 지출 경비 - 여름시즌 관광지 이용 비용
- 통계자료를 분석하기 전, 2021년 1월 기준 관광지별 요금에 대한 파일을 먼저 첨부해 당시 요금에 대해 언급한다.

In [4]:
import chardet
import pandas as pd

DATA_path = "/content/drive/MyDrive/세프/DATA/"
input_filename = DATA_path + '관광지입장요금표(2022.1.1).csv'

# 파일의 인코딩을 감지
with open(input_filename, 'rb') as f:
    result = chardet.detect(f.read())

# 감지된 인코딩 출력
detected_encoding = result['encoding']
print(f"Detected Encoding: {detected_encoding}")

# 파일을 읽고 새로운 인코딩으로 저장
df = pd.read_csv(input_filename, encoding=detected_encoding)
output_filename = DATA_path + '관광지입장요금표_2022.csv'
df.to_csv(output_filename, encoding='utf-8', index=False)

print(f"File converted to 'utf-8' and saved as {output_filename}")

Detected Encoding: EUC-KR
File converted to 'utf-8' and saved as /content/drive/MyDrive/세프/DATA/관광지입장요금표_2022.csv

In [5]:
fee_2022 = pd.read_csv(DATA_path + '관광지입장요금표_2022.csv')
fee_2022

            관광지명   성인 요금  청소년 요금  어린이 요금   노인 요금 국가 유공자 요금    장애인 요금
0         고흐의 정원  12,000  10,000   8,000     NaN     8,000     8,000
1       공룡휴게소박물관  10,000  10,000  10,000     NaN       NaN       NaN
2        교래자연휴양림   1,000     600     NaN     NaN       NaN       NaN
3          교육박물관      무료      무료      무료      무료        무료        무료
4        국립제주박물관      무료      무료      무료      무료        무료        무료
..           ...     ...     ...     ...     ...       ...       ...
172    헬로키티 아일랜드  14,000  13,000  11,000  10,000    10,000    10,000
173          휴애리  13,000  11,000  10,000   6,500     6,500     6,500
174          화조원  18,000  16,000  14,000  14,000    10,000  4,000 할인
175          환상숲   5,000   4,000   4,000   5,000     5,000     5,000
176  힐링카약파크 비체올린  14,000  13,000  12,000  12,000    12,000    12,000

[177 rows x 7 columns]