# 2022년

## 데이터 전처리

### 데이터 수집 비율
- 2022년도 여름 시즌 제주 여행자를 대상으로 한 방문 관광객 실태조사에서 응답자 프로파일을 가져옴.
  + 응답자 프로파일의 카테고리 중	월 평균 가구소득 카테고리만 수집함.
- **해당 연도의 데이터 수집 대상 비율을 명시해 앞으로 다룰 데이터들이 어떤 방식으로 추출되었는지 설명함.**

In [5]:
import pandas as pd

DATA_path = '/content/drive/MyDrive/세프/DATA/'

profile_df_2022 = pd.read_excel(DATA_path + '2022년 제주방문 응답자 프로파일 - 데이터 설명용.xlsx')
profile_df_2022.head()

  table Unnamed: 1 Unnamed: 2
0   NaN        NaN         전체
1   NaN        NaN        사례수
2    전체        NaN        629
3    권역     서울/경인권        420
4    권역        경상권        114

In [6]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수'}

profile_df_2022 = profile_df_2022.rename(columns = columns)
profile_df_2022.head()

  분석 카테고리 세부 카테고리  사례수
0     NaN     NaN   전체
1     NaN     NaN  사례수
2      전체     NaN  629
3      권역  서울/경인권  420
4      권역     경상권  114

In [7]:
profile_df_2022 = profile_df_2022.drop(index = range(0, 21)).reset_index(drop=True)
profile_df_2022

      분석 카테고리    세부 카테고리  사례수
0   월 평균 가구소득   400만원 미만   98
1   월 평균 가구소득  400-599만원  200
2   월 평균 가구소득  600-799만원  154
3   월 평균 가구소득   800만원 이상  177
4        거주지역      서울특별시  297
5        거주지역      부산광역시   52
6        거주지역      대구광역시   28
7        거주지역      인천광역시   33
8        거주지역      광주광역시   24
9        거주지역      대전광역시   24
10       거주지역      울산광역시   15
11       거주지역    세종특별자치도    1
12       거주지역        경기도   90
13       거주지역        강원도    8
14       거주지역        충청도   20
15       거주지역        전라도   18
16       거주지역        경상도   19

- 전처리가 완료된 응답자 프로파일.
  + 월 평균 가구소득 별로 나눠진 사례들의 비율이 극악한 차이는 보이지 않는다.

In [8]:
profile_df_2022 = profile_df_2022.drop(index = range(4, 17)).reset_index(drop=True)
profile_df_2022

     분석 카테고리    세부 카테고리  사례수
0  월 평균 가구소득   400만원 미만   98
1  월 평균 가구소득  400-599만원  200
2  월 평균 가구소득  600-799만원  154
3  월 평균 가구소득   800만원 이상  177

### 1인당 지출 경비 전처리
- 1인당 지출 경비에 대한 카테고리 : 숙박 부분, 식음료 부분, 관광지 이용료 부분
- **1인당 지출 경비 부분이 지출 기준인원 항목의 하위 항목으로 분류되어 있어 응답자 프로파일처럼 해당 데이터의 비율을 명시함.**

In [10]:
expenditure_standard_2022 = pd.read_excel(DATA_path + '2022년 지출 기준인원 - 1인당 지출 경비에 대한 상위 항목.xlsx')
expenditure_standard_2022.head()

,table,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균(명)
1,전체,NaN,629,7.8,32.4,25,28.1,4.9,1.1,0.2,0.3,0.2,3
2,권역,서울/경인권,420,7.6,34.5,27.6,23.8,4,1.7,0.2,0.5,0,2.9
3,권역,경상권,114,9.6,32.5,16.7,35.1,5.3,0,0,0,0.9,3
4,권역,호남권,42,9.5,23.8,23.8,33.3,9.5,0,0,0,0,3.1

In [11]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '1명',
           'Unnamed: 4' : '2명',
           'Unnamed: 5' : '3명',
           'Unnamed: 6' : '4명',
           'Unnamed: 7' : '5명',
           'Unnamed: 8' : '6명',
           'Unnamed: 9' : '7명',
           'Unnamed: 10' : '8명',
           'Unnamed: 11' : '9명',
           'Unnamed: 12' : '평균'}

expenditure_standard_2022 = expenditure_standard_2022.rename(columns = columns)
expenditure_standard_2022

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균
0,NaN,NaN,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균(명)
1,전체,NaN,629,7.8,32.4,25,28.1,4.9,1.1,0.2,0.3,0.2,3
2,권역,서울/경인권,420,7.6,34.5,27.6,23.8,4,1.7,0.2,0.5,0,2.9
3,권역,경상권,114,9.6,32.5,16.7,35.1,5.3,0,0,0,0.9,3
4,권역,호남권,42,9.5,23.8,23.8,33.3,9.5,0,0,0,0,3.1
5,권역,충청/강원권,53,3.8,22.6,22.6,43.4,7.5,0,0,0,0,3.3
6,성별,남자,366,9.8,29.8,25.1,28.7,4.4,1.4,0.3,0.3,0.3,3
7,성별,여자,263,4.9,36.1,24.7,27.4,5.7,0.8,0,0.4,0,3
8,연령,15~20세,13,0,30.8,30.8,38.5,0,0,0,0,0,3.1
9,연령,21~30세,108,13,48.1,15.7,17.6,3.7,0.9,0,0.9,0,2.6
10,연령,31~40세,200,7.5,31,30,26.5,3.5,1,0.5,0,0,2.9
11,연령,41~50세,176,4.5,18.2,27.8,40.9,6.2,1.1,0,0.6,0.6,3.4
12,연령,51~60세,92,9.8,34.8,25,21.7,7.6,1.1,0,0,0,2.9
13,연령,61세 이상,40,7.5,55,10,20,5,2.5,0,0,0,2.7
14,직업,학생,30,10,30,26.7,26.7,3.3,3.3,0,0,0,2.9
15,직업,사무/전문직,442,7.9,32.1,24.2,28.5,5.7,0.9,0.2,0.2,0.2,3
16,직업,판매/기술직,66,7.6,25.8,34.8,27.3,3,0,0,1.5,0,3
17,직업,자영업,31,3.2,38.7,22.6,32.3,0,3.2,0,0,0,3
18,직업,전업주부,38,5.3,31.6,28.9,26.3,7.9,0,0,0,0,3
19,직업,기타(무직 등),22,13.6,54.5,4.5,22.7,0,4.5,0,0,0,2.5
20,월 평균 가구소득,400만원 미만,98,11.2,46.9,21.4,19.4,1,0,0,0,0,2.5
21,월 평균 가구소득,400-599만원,200,7.5,27.5,27.5,31.5,4.5,1,0,0.5,0,3
22,월 평균 가구소득,600-799만원,154,8.4,27.3,24,33.1,3.9,2.6,0.6,0,0,3.1
23,월 평균 가구소득,800만원 이상,177,5.6,34.5,24.9,24.9,8.5,0.6,0,0.6,0.6,3
24,거주지역,서울특별시,297,7.7,36,29.3,20.2,4.7,1,0.3,0.7,0,2.9
25,거주지역,부산광역시,52,5.8,46.2,9.6,30.8,5.8,0,0,0,1.9,3
26,거주지역,대구광역시,28,10.7,25,17.9,42.9,3.6,0,0,0,0,3
27,거주지역,인천광역시,33,3,33.3,15.2,36.4,3,9.1,0,0,0,3.3
28,거주지역,광주광역시,24,16.7,25,12.5,37.5,8.3,0,0,0,0,3
29,거주지역,대전광역시,24,4.2,29.2,20.8,37.5,8.3,0,0,0,0,3.2
30,거주지역,울산광역시,15,6.7,26.7,26.7,40,0,0,0,0,0,3
31,거주지역,세종특별자치도,1,0,0,0,0,100,0,0,0,0,5
32,거주지역,경기도,90,8.9,30,26.7,31.1,2.2,1.1,0,0,0,2.9
33,거주지역,강원도,8,0,12.5,37.5,37.5,12.5,0,0,0,0,3.5
34,거주지역,충청도,20,5,20,20,55,0,0,0,0,0,3.2
35,거주지역,전라도,18,0,22.2,38.9,27.8,11.1,0,0,0,0,3.3
36,거주지역,경상도,19,21.1,10.5,26.3,31.6,10.5,0,0,0,0,3
37,BASE : 제주여행 방문자(SQ1=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
expenditure_standard_2022 = expenditure_standard_2022.drop(index = range(0, 20)).reset_index(drop=True)

expenditure_standard_2022

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균
0,월 평균 가구소득,400만원 미만,98,11.2,46.9,21.4,19.4,1,0,0,0,0,2.5
1,월 평균 가구소득,400-599만원,200,7.5,27.5,27.5,31.5,4.5,1,0,0.5,0,3
2,월 평균 가구소득,600-799만원,154,8.4,27.3,24,33.1,3.9,2.6,0.6,0,0,3.1
3,월 평균 가구소득,800만원 이상,177,5.6,34.5,24.9,24.9,8.5,0.6,0,0.6,0.6,3
4,거주지역,서울특별시,297,7.7,36,29.3,20.2,4.7,1,0.3,0.7,0,2.9
5,거주지역,부산광역시,52,5.8,46.2,9.6,30.8,5.8,0,0,0,1.9,3
6,거주지역,대구광역시,28,10.7,25,17.9,42.9,3.6,0,0,0,0,3
7,거주지역,인천광역시,33,3,33.3,15.2,36.4,3,9.1,0,0,0,3.3
8,거주지역,광주광역시,24,16.7,25,12.5,37.5,8.3,0,0,0,0,3
9,거주지역,대전광역시,24,4.2,29.2,20.8,37.5,8.3,0,0,0,0,3.2
10,거주지역,울산광역시,15,6.7,26.7,26.7,40,0,0,0,0,0,3
11,거주지역,세종특별자치도,1,0,0,0,0,100,0,0,0,0,5
12,거주지역,경기도,90,8.9,30,26.7,31.1,2.2,1.1,0,0,0,2.9
13,거주지역,강원도,8,0,12.5,37.5,37.5,12.5,0,0,0,0,3.5
14,거주지역,충청도,20,5,20,20,55,0,0,0,0,0,3.2
15,거주지역,전라도,18,0,22.2,38.9,27.8,11.1,0,0,0,0,3.3
16,거주지역,경상도,19,21.1,10.5,26.3,31.6,10.5,0,0,0,0,3
17,BASE : 제주여행 방문자(SQ1=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 전처리가 완료된 지출 기준인원.
  + 2명의 비율이 가장 높고 6~9명의 비율이 거의 없는 수치에 가까운 결과를 보인다.

In [13]:
expenditure_standard_2022 = expenditure_standard_2022.drop(index = range(4, 18)).reset_index(drop=True)

expenditure_standard_2022

,분석 카테고리,세부 카테고리,사례수,1명,2명,3명,4명,5명,6명,7명,8명,9명,평균
0,월 평균 가구소득,400만원 미만,98,11.2,46.9,21.4,19.4,1,0,0,0,0,2.5
1,월 평균 가구소득,400-599만원,200,7.5,27.5,27.5,31.5,4.5,1,0,0.5,0,3
2,월 평균 가구소득,600-799만원,154,8.4,27.3,24,33.1,3.9,2.6,0.6,0,0,3.1
3,월 평균 가구소득,800만원 이상,177,5.6,34.5,24.9,24.9,8.5,0.6,0,0.6,0.6,3

#### 1인당 지출 경비 - 여름시즌 숙박 비용
- 해당 파일에 대한 전처리

In [17]:
accommodation_cost_2022 = pd.read_excel(DATA_path + '2022년 1인당 지출경비 - 여름시즌 숙박비.xlsx')
accommodation_cost_2022

,table,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,사례수,5만원 미만,5만원 이상 ~ 10만원 미만,10만원 이상 ~ 30만원 미만,30만원 이상 ~ 50만원 미만,50만원 이상 ~ 100만원 미만,해당없음(0원 일 때),평균(만원),합계(만원)
1,전체,NaN,106,18.9,33,34,3.8,0.9,9.4,9.5,1008.2
2,권역,서울/경인권,74,16.2,33.8,39.2,1.4,0,9.5,8.9,659
3,권역,경상권,13,15.4,46.2,15.4,7.7,0,15.4,9.1,118
4,권역,호남권,9,22.2,33.3,44.4,0,0,0,9.5,85.4
5,권역,충청/강원권,10,40,10,10,20,10,10,14.6,145.7
6,성별,남자,59,22,32.2,30.5,5.1,1.7,8.5,9.7,574.1
7,성별,여자,47,14.9,34,38.3,2.1,0,10.6,9.2,434
8,연령,15~20세,4,25,25,0,0,0,50,1.8,7
9,연령,21~30세,10,10,60,20,0,0,10,6.8,68.2
10,연령,31~40세,25,20,32,32,0,4,12,9.4,235
11,연령,41~50세,43,18.6,34.9,39.5,2.3,0,4.7,9.5,406.8
12,연령,51~60세,17,23.5,17.6,41.2,11.8,0,5.9,12.6,214.2
13,연령,61세 이상,7,14.3,28.6,28.6,14.3,0,14.3,11,77
14,직업,학생,6,0,50,0,0,0,50,3.4,20.5
15,직업,사무/전문직,63,20.6,34.9,33.3,4.8,1.6,4.8,10.2,640.6
16,직업,판매/기술직,7,28.6,14.3,57.1,0,0,0,11.1,77.5
17,직업,자영업,10,10,30,40,0,0,20,6.9,69.3
18,직업,전업주부,14,21.4,35.7,35.7,0,0,7.1,9.3,129.9
19,직업,기타(무직 등),6,16.7,16.7,33.3,16.7,0,16.7,11.7,70.3
20,월 평균 가구소득,400만원 미만,21,23.8,23.8,19,0,0,33.3,5,104.1
21,월 평균 가구소득,400-599만원,28,21.4,39.3,39.3,0,0,0,9.4,264.2
22,월 평균 가구소득,600-799만원,24,12.5,37.5,37.5,8.3,0,4.2,10.5,251.5
23,월 평균 가구소득,800만원 이상,33,18.2,30.3,36.4,6.1,3,6.1,11.8,388.3
24,거주지역,서울특별시,31,9.7,25.8,45.2,3.2,0,16.1,10,310.2
25,거주지역,부산광역시,3,0,33.3,33.3,33.3,0,0,17.1,51.3
26,거주지역,대구광역시,5,0,80,20,0,0,0,10.6,52.9
27,거주지역,인천광역시,9,33.3,22.2,33.3,0,0,11.1,6.4,57.4
28,거주지역,광주광역시,2,50,50,0,0,0,0,5.9,11.8
29,거주지역,대전광역시,1,100,0,0,0,0,0,2,2
30,거주지역,울산광역시,1,100,0,0,0,0,0,2.5,2.5
31,거주지역,세종특별자치도,1,100,0,0,0,0,0,2.5,2.5
32,거주지역,경기도,34,17.6,44.1,35.3,0,0,2.9,8.6,291.4
33,거주지역,강원도,4,0,0,25,25,25,25,23.8,95
34,거주지역,충청도,4,50,25,0,25,0,0,11.6,46.2
35,거주지역,전라도,7,14.3,28.6,57.1,0,0,0,10.5,73.7
36,거주지역,경상도,4,25,25,0,0,0,50,2.8,11.2
37,BASE : 타 지역 여행 대체자(SQ2=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '5만원 미만',
           'Unnamed: 4' : '5만원 이상-10만원 미만',
           'Unnamed: 5' : '10만원 이상-30만원 미만',
           'Unnamed: 6' : '30만원 이상-50만원 미만',
           'Unnamed: 7' : '50만원 이상-100만원 미만',
           'Unnamed: 8' : '해당없음(0원)',
           'Unnamed: 9' : '평균',
           'Unnamed: 10' : '합계'}

accommodation_cost_2022 = accommodation_cost_2022.rename(columns = columns)
accommodation_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원 이상-10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,해당없음(0원),평균,합계
0,NaN,NaN,사례수,5만원 미만,5만원 이상 ~ 10만원 미만,10만원 이상 ~ 30만원 미만,30만원 이상 ~ 50만원 미만,50만원 이상 ~ 100만원 미만,해당없음(0원 일 때),평균(만원),합계(만원)
1,전체,NaN,106,18.9,33,34,3.8,0.9,9.4,9.5,1008.2
2,권역,서울/경인권,74,16.2,33.8,39.2,1.4,0,9.5,8.9,659
3,권역,경상권,13,15.4,46.2,15.4,7.7,0,15.4,9.1,118
4,권역,호남권,9,22.2,33.3,44.4,0,0,0,9.5,85.4
5,권역,충청/강원권,10,40,10,10,20,10,10,14.6,145.7
6,성별,남자,59,22,32.2,30.5,5.1,1.7,8.5,9.7,574.1
7,성별,여자,47,14.9,34,38.3,2.1,0,10.6,9.2,434
8,연령,15~20세,4,25,25,0,0,0,50,1.8,7
9,연령,21~30세,10,10,60,20,0,0,10,6.8,68.2
10,연령,31~40세,25,20,32,32,0,4,12,9.4,235
11,연령,41~50세,43,18.6,34.9,39.5,2.3,0,4.7,9.5,406.8
12,연령,51~60세,17,23.5,17.6,41.2,11.8,0,5.9,12.6,214.2
13,연령,61세 이상,7,14.3,28.6,28.6,14.3,0,14.3,11,77
14,직업,학생,6,0,50,0,0,0,50,3.4,20.5
15,직업,사무/전문직,63,20.6,34.9,33.3,4.8,1.6,4.8,10.2,640.6
16,직업,판매/기술직,7,28.6,14.3,57.1,0,0,0,11.1,77.5
17,직업,자영업,10,10,30,40,0,0,20,6.9,69.3
18,직업,전업주부,14,21.4,35.7,35.7,0,0,7.1,9.3,129.9
19,직업,기타(무직 등),6,16.7,16.7,33.3,16.7,0,16.7,11.7,70.3
20,월 평균 가구소득,400만원 미만,21,23.8,23.8,19,0,0,33.3,5,104.1
21,월 평균 가구소득,400-599만원,28,21.4,39.3,39.3,0,0,0,9.4,264.2
22,월 평균 가구소득,600-799만원,24,12.5,37.5,37.5,8.3,0,4.2,10.5,251.5
23,월 평균 가구소득,800만원 이상,33,18.2,30.3,36.4,6.1,3,6.1,11.8,388.3
24,거주지역,서울특별시,31,9.7,25.8,45.2,3.2,0,16.1,10,310.2
25,거주지역,부산광역시,3,0,33.3,33.3,33.3,0,0,17.1,51.3
26,거주지역,대구광역시,5,0,80,20,0,0,0,10.6,52.9
27,거주지역,인천광역시,9,33.3,22.2,33.3,0,0,11.1,6.4,57.4
28,거주지역,광주광역시,2,50,50,0,0,0,0,5.9,11.8
29,거주지역,대전광역시,1,100,0,0,0,0,0,2,2
30,거주지역,울산광역시,1,100,0,0,0,0,0,2.5,2.5
31,거주지역,세종특별자치도,1,100,0,0,0,0,0,2.5,2.5
32,거주지역,경기도,34,17.6,44.1,35.3,0,0,2.9,8.6,291.4
33,거주지역,강원도,4,0,0,25,25,25,25,23.8,95
34,거주지역,충청도,4,50,25,0,25,0,0,11.6,46.2
35,거주지역,전라도,7,14.3,28.6,57.1,0,0,0,10.5,73.7
36,거주지역,경상도,4,25,25,0,0,0,50,2.8,11.2
37,BASE : 타 지역 여행 대체자(SQ2=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
accommodation_cost_2022 = accommodation_cost_2022.drop(index = range(0, 20)).reset_index(drop=True)

accommodation_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원 이상-10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,해당없음(0원),평균,합계
0,월 평균 가구소득,400만원 미만,21,23.8,23.8,19,0,0,33.3,5,104.1
1,월 평균 가구소득,400-599만원,28,21.4,39.3,39.3,0,0,0,9.4,264.2
2,월 평균 가구소득,600-799만원,24,12.5,37.5,37.5,8.3,0,4.2,10.5,251.5
3,월 평균 가구소득,800만원 이상,33,18.2,30.3,36.4,6.1,3,6.1,11.8,388.3
4,거주지역,서울특별시,31,9.7,25.8,45.2,3.2,0,16.1,10,310.2
5,거주지역,부산광역시,3,0,33.3,33.3,33.3,0,0,17.1,51.3
6,거주지역,대구광역시,5,0,80,20,0,0,0,10.6,52.9
7,거주지역,인천광역시,9,33.3,22.2,33.3,0,0,11.1,6.4,57.4
8,거주지역,광주광역시,2,50,50,0,0,0,0,5.9,11.8
9,거주지역,대전광역시,1,100,0,0,0,0,0,2,2
10,거주지역,울산광역시,1,100,0,0,0,0,0,2.5,2.5
11,거주지역,세종특별자치도,1,100,0,0,0,0,0,2.5,2.5
12,거주지역,경기도,34,17.6,44.1,35.3,0,0,2.9,8.6,291.4
13,거주지역,강원도,4,0,0,25,25,25,25,23.8,95
14,거주지역,충청도,4,50,25,0,25,0,0,11.6,46.2
15,거주지역,전라도,7,14.3,28.6,57.1,0,0,0,10.5,73.7
16,거주지역,경상도,4,25,25,0,0,0,50,2.8,11.2
17,BASE : 타 지역 여행 대체자(SQ2=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 전처리가 완료된 숙박 비용에 대한 1인당 지출 경비.
  + 월 평균 가구소득에 따라 큰차이는 없으며, 5만원 이상-10만원 미만과 10만원 이상-30만원 미만의 비율이 가장 높은 결과를 보인다.

In [20]:
accommodation_cost_2022 = accommodation_cost_2022.drop(index = range(4, 18)).reset_index(drop=True)

accommodation_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원 이상-10만원 미만,10만원 이상-30만원 미만,30만원 이상-50만원 미만,50만원 이상-100만원 미만,해당없음(0원),평균,합계
0,월 평균 가구소득,400만원 미만,21,23.8,23.8,19,0,0,33.3,5,104.1
1,월 평균 가구소득,400-599만원,28,21.4,39.3,39.3,0,0,0,9.4,264.2
2,월 평균 가구소득,600-799만원,24,12.5,37.5,37.5,8.3,0,4.2,10.5,251.5
3,월 평균 가구소득,800만원 이상,33,18.2,30.3,36.4,6.1,3,6.1,11.8,388.3

#### 1인당 지출 경비 - 여름시즌 식음료 비용
- 해당 파일에 대한 전처리

In [26]:
food_cost_2022 = pd.read_excel(DATA_path + '2022년 1인당 지출경비 - 여름시즌 식음료비.xlsx')
food_cost_2022.head()

,table,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,사례수,5만원 미만,5만원 이상 ~ 10만원 미만,10만원 이상 ~ 30만원 미만,해당없음(0원 일 때),평균(만원),합계(만원)
1,전체,NaN,106,24.5,32.1,42.5,0.9,8.4,894.2
2,권역,서울/경인권,74,21.6,29.7,47.3,1.4,8.5,628
3,권역,경상권,13,30.8,46.2,23.1,0,8.2,106.2
4,권역,호남권,9,22.2,44.4,33.3,0,7.4,66.8

In [27]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '5만원 미만',
           'Unnamed: 4' : '5만원이상-10만원 미만',
           'Unnamed: 5' : '10만원 이상-30만원 미만',
           'Unnamed: 6' : '해당없음(0원)',
           'Unnamed: 7' : '평균',
           'Unnamed: 8' : '합계'}

food_cost_2022 = food_cost_2022.rename(columns = columns)
food_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원이상-10만원 미만,10만원 이상-30만원 미만,해당없음(0원),평균,합계
0,NaN,NaN,사례수,5만원 미만,5만원 이상 ~ 10만원 미만,10만원 이상 ~ 30만원 미만,해당없음(0원 일 때),평균(만원),합계(만원)
1,전체,NaN,106,24.5,32.1,42.5,0.9,8.4,894.2
2,권역,서울/경인권,74,21.6,29.7,47.3,1.4,8.5,628
3,권역,경상권,13,30.8,46.2,23.1,0,8.2,106.2
4,권역,호남권,9,22.2,44.4,33.3,0,7.4,66.8
5,권역,충청/강원권,10,40,20,40,0,9.3,93.2
6,성별,남자,59,25.4,32.2,42.4,0,8.3,492
7,성별,여자,47,23.4,31.9,42.6,2.1,8.6,402.1
8,연령,15~20세,4,100,0,0,0,2.6,10.5
9,연령,21~30세,10,50,30,20,0,6.1,61.2
10,연령,31~40세,25,24,40,36,0,7.8,194.2
11,연령,41~50세,43,23.3,34.9,41.9,0,8.4,362.8
12,연령,51~60세,17,5.9,29.4,64.7,0,11.3,192.2
13,연령,61세 이상,7,0,14.3,71.4,14.3,10.5,73.4
14,직업,학생,6,83.3,16.7,0,0,2.5,15
15,직업,사무/전문직,63,22.2,34.9,42.9,0,8.5,533.7
16,직업,판매/기술직,7,14.3,42.9,42.9,0,11.3,79.2
17,직업,자영업,10,10,30,60,0,10,100.3
18,직업,전업주부,14,14.3,28.6,50,7.1,9.3,129.8
19,직업,기타(무직 등),6,50,16.7,33.3,0,6,36.2
20,월 평균 가구소득,400만원 미만,21,42.9,28.6,28.6,0,6.8,142.1
21,월 평균 가구소득,400-599만원,28,17.9,46.4,35.7,0,8.7,242.4
22,월 평균 가구소득,600-799만원,24,25,29.2,45.8,0,9.1,218.5
23,월 평균 가구소득,800만원 이상,33,18.2,24.2,54.5,3,8.8,291.1
24,거주지역,서울특별시,31,19.4,22.6,54.8,3.2,7.8,242.4
25,거주지역,부산광역시,3,0,33.3,66.7,0,13.4,40.3
26,거주지역,대구광역시,5,40,40,20,0,7.6,38
27,거주지역,인천광역시,9,22.2,33.3,44.4,0,10.2,91.7
28,거주지역,광주광역시,2,0,100,0,0,7.8,15.5
29,거주지역,대전광역시,1,100,0,0,0,4,4
30,거주지역,울산광역시,1,0,100,0,0,5,5
31,거주지역,세종특별자치도,1,100,0,0,0,1.2,1.2
32,거주지역,경기도,34,23.5,35.3,41.2,0,8.6,293.9
33,거주지역,강원도,4,25,0,75,0,12.1,48.5
34,거주지역,충청도,4,25,50,25,0,9.9,39.5
35,거주지역,전라도,7,28.6,28.6,42.9,0,7.3,51.2
36,거주지역,경상도,4,50,50,0,0,5.7,22.9
37,BASE : 타 지역 여행 대체자(SQ2=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
food_cost_2022 = food_cost_2022.drop(index = range(0, 20)).reset_index(drop=True)

food_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원이상-10만원 미만,10만원 이상-30만원 미만,해당없음(0원),평균,합계
0,월 평균 가구소득,400만원 미만,21,42.9,28.6,28.6,0,6.8,142.1
1,월 평균 가구소득,400-599만원,28,17.9,46.4,35.7,0,8.7,242.4
2,월 평균 가구소득,600-799만원,24,25,29.2,45.8,0,9.1,218.5
3,월 평균 가구소득,800만원 이상,33,18.2,24.2,54.5,3,8.8,291.1
4,거주지역,서울특별시,31,19.4,22.6,54.8,3.2,7.8,242.4
5,거주지역,부산광역시,3,0,33.3,66.7,0,13.4,40.3
6,거주지역,대구광역시,5,40,40,20,0,7.6,38
7,거주지역,인천광역시,9,22.2,33.3,44.4,0,10.2,91.7
8,거주지역,광주광역시,2,0,100,0,0,7.8,15.5
9,거주지역,대전광역시,1,100,0,0,0,4,4
10,거주지역,울산광역시,1,0,100,0,0,5,5
11,거주지역,세종특별자치도,1,100,0,0,0,1.2,1.2
12,거주지역,경기도,34,23.5,35.3,41.2,0,8.6,293.9
13,거주지역,강원도,4,25,0,75,0,12.1,48.5
14,거주지역,충청도,4,25,50,25,0,9.9,39.5
15,거주지역,전라도,7,28.6,28.6,42.9,0,7.3,51.2
16,거주지역,경상도,4,50,50,0,0,5.7,22.9
17,BASE : 타 지역 여행 대체자(SQ2=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 전처리가 완료된 식음료 비용에 대한 1인당 지출 경비.
  + 월 평균 가구소득이 400만원 미만인 가구의 소비금액은 5만원 미만의 소비가 가장 많았다.
  + 월 평균 가구소득이 400-599만원인 가구의 소비금액은 5만원 이상-10만원 미만의 소비가 가장 많았으면, 월 평균 가구소득이 그 이상인 가구들은 평균적으로 10만원 이상-30만원 미만의 소비 비율이 높은 것으로 나타났다.

In [29]:
food_cost_2022 = food_cost_2022.drop(index = range(4, 18)).reset_index(drop=True)

food_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원이상-10만원 미만,10만원 이상-30만원 미만,해당없음(0원),평균,합계
0,월 평균 가구소득,400만원 미만,21,42.9,28.6,28.6,0,6.8,142.1
1,월 평균 가구소득,400-599만원,28,17.9,46.4,35.7,0,8.7,242.4
2,월 평균 가구소득,600-799만원,24,25,29.2,45.8,0,9.1,218.5
3,월 평균 가구소득,800만원 이상,33,18.2,24.2,54.5,3,8.8,291.1

#### 1인당 지출 경비 - 여름시즌 관광지 이용 비용
- 통계자료를 분석하기 전, 2022년 1월 기준 관광지별 요금에 대한 파일을 먼저 첨부해 당시 요금에 대해 언급한다.

In [ ]:
import chardet
import pandas as pd

DATA_path = "/content/drive/MyDrive/세프/DATA/"
input_filename = DATA_path + '관광지입장요금표(2022.1.1).csv'

# 파일의 인코딩을 감지
with open(input_filename, 'rb') as f:
    result = chardet.detect(f.read())

# 감지된 인코딩 출력
detected_encoding = result['encoding']
print(f"Detected Encoding: {detected_encoding}")

# 파일을 읽고 새로운 인코딩으로 저장
df = pd.read_csv(input_filename, encoding=detected_encoding)
output_filename = DATA_path + '관광지입장요금표_2022.csv'
df.to_csv(output_filename, encoding='utf-8', index=False)

print(f"File converted to 'utf-8' and saved as {output_filename}")

Detected Encoding: EUC-KR
File converted to 'utf-8' and saved as /content/drive/MyDrive/세프/DATA/관광지입장요금표_2022.csv

- 전처리가 완료된 2022년도 관광지별 요금 (단체요금 X)
  + 2022년도 요금확인 용.

In [ ]:
fee_2022 = pd.read_csv(DATA_path + '관광지입장요금표_2022.csv')
fee_2022

            관광지명   성인 요금  청소년 요금  어린이 요금   노인 요금 국가 유공자 요금    장애인 요금
0         고흐의 정원  12,000  10,000   8,000     NaN     8,000     8,000
1       공룡휴게소박물관  10,000  10,000  10,000     NaN       NaN       NaN
2        교래자연휴양림   1,000     600     NaN     NaN       NaN       NaN
3          교육박물관      무료      무료      무료      무료        무료        무료
4        국립제주박물관      무료      무료      무료      무료        무료        무료
..           ...     ...     ...     ...     ...       ...       ...
172    헬로키티 아일랜드  14,000  13,000  11,000  10,000    10,000    10,000
173          휴애리  13,000  11,000  10,000   6,500     6,500     6,500
174          화조원  18,000  16,000  14,000  14,000    10,000  4,000 할인
175          환상숲   5,000   4,000   4,000   5,000     5,000     5,000
176  힐링카약파크 비체올린  14,000  13,000  12,000  12,000    12,000    12,000

[177 rows x 7 columns]

- 1인당 지출 경비 파일에 대한 전처리

In [30]:
culture_cost_2022 = pd.read_excel(DATA_path + '2022년 1인당 지출경비 - 여름시즌 관광지 이용료.xlsx')
culture_cost_2022.head()

,table,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,사례수,5만원 미만,5만원 이상 ~ 10만원 미만,10만원 이상 ~ 30만원 미만,해당없음(0원 일 때),평균(만원),합계(만원)
1,전체,NaN,106,53.8,12.3,6.6,27.4,2.5,263.2
2,권역,서울/경인권,74,51.4,12.2,6.8,29.7,2.4,177.9
3,권역,경상권,13,61.5,7.7,0,30.8,2,26.6
4,권역,호남권,9,55.6,22.2,11.1,11.1,3.7,33.7

In [31]:
columns = {'table' : '분석 카테고리',
           'Unnamed: 1' : '세부 카테고리',
           'Unnamed: 2' : '사례수',
           'Unnamed: 3' : '5만원 미만',
           'Unnamed: 4' : '5만원 이상-10만원 미만',
           'Unnamed: 5' : '10만원 이상-30만원 미만',
           'Unnamed: 6' : '해당없음(0원)',
           'Unnamed: 7' : '평균',
           'Unnamed: 8' : '합계'}

culture_cost_2022 = culture_cost_2022.rename(columns = columns)
culture_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원 이상-10만원 미만,10만원 이상-30만원 미만,해당없음(0원),평균,합계
0,NaN,NaN,사례수,5만원 미만,5만원 이상 ~ 10만원 미만,10만원 이상 ~ 30만원 미만,해당없음(0원 일 때),평균(만원),합계(만원)
1,전체,NaN,106,53.8,12.3,6.6,27.4,2.5,263.2
2,권역,서울/경인권,74,51.4,12.2,6.8,29.7,2.4,177.9
3,권역,경상권,13,61.5,7.7,0,30.8,2,26.6
4,권역,호남권,9,55.6,22.2,11.1,11.1,3.7,33.7
5,권역,충청/강원권,10,60,10,10,20,2.5,24.9
6,성별,남자,59,55.9,11.9,8.5,23.7,2.9,168.9
7,성별,여자,47,51.1,12.8,4.3,31.9,2,94.2
8,연령,15~20세,4,100,0,0,0,2.6,10.3
9,연령,21~30세,10,50,10,0,40,1.2,11.9
10,연령,31~40세,25,48,16,8,28,2.5,63.8
11,연령,41~50세,43,51.2,14,9.3,25.6,3,129.2
12,연령,51~60세,17,58.8,0,5.9,35.3,1.5,26.2
13,연령,61세 이상,7,57.1,28.6,0,14.3,3.1,21.8
14,직업,학생,6,83.3,0,0,16.7,1.8,10.6
15,직업,사무/전문직,63,52.4,17.5,7.9,22.2,2.8,179.3
16,직업,판매/기술직,7,57.1,0,14.3,28.6,2.7,18.6
17,직업,자영업,10,40,0,10,50,2.3,23.2
18,직업,전업주부,14,50,7.1,0,42.9,1,13.8
19,직업,기타(무직 등),6,66.7,16.7,0,16.7,2.9,17.7
20,월 평균 가구소득,400만원 미만,21,52.4,0,4.8,42.9,1.6,33.4
21,월 평균 가구소득,400-599만원,28,53.6,10.7,10.7,25,2.9,80.4
22,월 평균 가구소득,600-799만원,24,54.2,16.7,0,29.2,1.8,44.1
23,월 평균 가구소득,800만원 이상,33,54.5,18.2,9.1,18.2,3.2,105.3
24,거주지역,서울특별시,31,41.9,16.1,3.2,38.7,2,62.2
25,거주지역,부산광역시,3,33.3,33.3,0,33.3,3.1,9.2
26,거주지역,대구광역시,5,60,0,0,40,1.5,7.4
27,거주지역,인천광역시,9,44.4,11.1,0,44.4,1.3,11.3
28,거주지역,광주광역시,2,100,0,0,0,1.8,3.5
29,거주지역,대전광역시,1,100,0,0,0,2,2
30,거주지역,울산광역시,1,100,0,0,0,1.2,1.2
31,거주지역,세종특별자치도,1,100,0,0,0,1.2,1.2
32,거주지역,경기도,34,61.8,8.8,11.8,17.6,3.1,104.5
33,거주지역,강원도,4,50,0,25,25,3.8,15
34,거주지역,충청도,4,50,25,0,25,1.7,6.7
35,거주지역,전라도,7,42.9,28.6,14.3,14.3,4.3,30.2
36,거주지역,경상도,4,75,0,0,25,2.2,8.8
37,BASE : 타 지역 여행 대체자(SQ2=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
culture_cost_2022 = culture_cost_2022.drop(index = range(0, 20)).reset_index(drop=True)

culture_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원 이상-10만원 미만,10만원 이상-30만원 미만,해당없음(0원),평균,합계
0,월 평균 가구소득,400만원 미만,21,52.4,0,4.8,42.9,1.6,33.4
1,월 평균 가구소득,400-599만원,28,53.6,10.7,10.7,25,2.9,80.4
2,월 평균 가구소득,600-799만원,24,54.2,16.7,0,29.2,1.8,44.1
3,월 평균 가구소득,800만원 이상,33,54.5,18.2,9.1,18.2,3.2,105.3
4,거주지역,서울특별시,31,41.9,16.1,3.2,38.7,2,62.2
5,거주지역,부산광역시,3,33.3,33.3,0,33.3,3.1,9.2
6,거주지역,대구광역시,5,60,0,0,40,1.5,7.4
7,거주지역,인천광역시,9,44.4,11.1,0,44.4,1.3,11.3
8,거주지역,광주광역시,2,100,0,0,0,1.8,3.5
9,거주지역,대전광역시,1,100,0,0,0,2,2
10,거주지역,울산광역시,1,100,0,0,0,1.2,1.2
11,거주지역,세종특별자치도,1,100,0,0,0,1.2,1.2
12,거주지역,경기도,34,61.8,8.8,11.8,17.6,3.1,104.5
13,거주지역,강원도,4,50,0,25,25,3.8,15
14,거주지역,충청도,4,50,25,0,25,1.7,6.7
15,거주지역,전라도,7,42.9,28.6,14.3,14.3,4.3,30.2
16,거주지역,경상도,4,75,0,0,25,2.2,8.8
17,BASE : 타 지역 여행 대체자(SQ2=1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 전처리가 완료된 관광지 이용 비용에 대한 1인당 지출 경비.
  + 5만원 미만의 비율이 높게 나오는 것으로 보인다.

In [33]:
culture_cost_2022 = culture_cost_2022.drop(index = range(4, 18)).reset_index(drop=True)

culture_cost_2022

,분석 카테고리,세부 카테고리,사례수,5만원 미만,5만원 이상-10만원 미만,10만원 이상-30만원 미만,해당없음(0원),평균,합계
0,월 평균 가구소득,400만원 미만,21,52.4,0,4.8,42.9,1.6,33.4
1,월 평균 가구소득,400-599만원,28,53.6,10.7,10.7,25,2.9,80.4
2,월 평균 가구소득,600-799만원,24,54.2,16.7,0,29.2,1.8,44.1
3,월 평균 가구소득,800만원 이상,33,54.5,18.2,9.1,18.2,3.2,105.3